/**
 * Writes docs/SLIDERS.md: every module, its picture kind, and whether its page shows sliders
 * (the policy in `src/components/module/sliderPolicy.ts`, or the module's own setting).
 *
 *   pnpm docs:sliders
 *
 * Skipped unless WRITE_DOCS=1. Rerun after adding modules or changing the policy.
 */
import { showsSliders, sliderReason } from '@/components/module/sliderPolicy';

import { TESTED_MODULES } from '..';

declare const require: (name: string) => { writeFileSync: (path: string, text: string) => void };
const env: Record<string, string | undefined> =
  (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env ?? {};

(env.WRITE_DOCS ? test : test.skip)('writes the sliders table', () => {
  const rows = TESTED_MODULES.map((m) => ({
    id: m.id,
    kind: m.representation.kind,
    on: showsSliders(m),
    why: sliderReason(m),
  }));
  const on = rows.filter((r) => r.on).length;
  const byKind = new Map<string, { on: boolean; count: number; why: string }>();
  for (const r of rows) {
    const k = byKind.get(r.kind) ?? { on: r.on, count: 0, why: r.why };
    k.count++;
    byKind.set(r.kind, k);
  }
  const overrides = TESTED_MODULES.filter((m) => m.sliders !== undefined);
  const text = [
    '# Sliders: which pages show them',
    '',
    'Generated by `pnpm docs:sliders` from the policy in `src/components/module/sliderPolicy.ts`.',
    'A slider row appears only where sweeping a value teaches something the input boxes',
    "can't and the picture has no handle or tap of its own for that value. Every other page",
    'has the input boxes (and the picture’s own handles or taps) alone. A module can override',
    'its kind with `sliders: true | false`.',
    '',
    `${on} of ${rows.length} pages show sliders.`,
    '',
    '## By picture kind',
    '',
    '| Kind | Pages | Sliders | Why |',
    '| --- | ---: | :---: | --- |',
    ...[...byKind]
      .sort((a, b) => a[0].localeCompare(b[0]))
      .map(([kind, k]) => `| ${kind} | ${k.count} | ${k.on ? 'yes' : 'no'} | ${k.why} |`),
    '',
    '## Modules that override their kind',
    '',
    ...(overrides.length
      ? overrides.map((m) => `- ${m.id}: sliders ${m.sliders ? 'shown' : 'hidden'}`)
      : ['(none)']),
    '',
    '## Every page',
    '',
    '| Module | Kind | Sliders |',
    '| --- | --- | :---: |',
    ...rows.map((r) => `| ${r.id} | ${r.kind} | ${r.on ? 'yes' : 'no'} |`),
    '',
  ].join('\n');
  require('fs').writeFileSync('docs/SLIDERS.md', text);
  expect(rows.length).toBeGreaterThan(0);
});
