// Generated by scripts/render-art.mjs from its drawing of B16; change the drawing there and rerun.
import { View } from 'react-native';
import Svg, { Circle, Ellipse, G, Line, Path, Rect } from 'react-native-svg';

import { usePalette } from '@/theme';

/**
 * B16: An empty bookshelf with one book leaning against its side.
 * Artboard 240 x 160; `width` scales it. Decorative (hidden from screen readers) unless
 * a `label` is given. Colours come from the palette, so one drawing serves light and dark.
 */
export function EmptyShelf({ width = 240, label }: { width?: number; label?: string }) {
  const c = usePalette();
  return (
    <View
      role={label ? 'img' : undefined}
      aria-label={label}
      aria-hidden={!label}
      importantForAccessibility={label ? 'yes' : 'no-hide-descendants'}
    >
      <Svg width={width} height={width * 0.6666666666666666} viewBox={'0 0 240 160'}>
        <G strokeLinecap="round" strokeLinejoin="round">
          <Circle cx={120} cy={80} r={70} fill={c.accentSoft} />
          <Ellipse cx={120} cy={146} rx={72} ry={4} fill={c.artShade} />
          <Path
            d="M57 22H183Q188 22 188 27V141Q188 146 183 146H57Q52 146 52 141V27Q52 22 57 22Z"
            fill={c.artWood}
          />
          <Path
            d="M57 22H183Q188 22 188 27V141Q188 146 183 146H57Q52 146 52 141V27Q52 22 57 22Z"
            fill="none"
            stroke={c.artInk}
            strokeWidth={2.25}
          />
          <Path
            d="M64 32H176Q178 32 178 34V80Q178 82 176 82H64Q62 82 62 80V34Q62 32 64 32Z"
            fill={c.artShade}
          />
          <Path
            d="M64 32H176Q178 32 178 34V80Q178 82 176 82H64Q62 82 62 80V34Q62 32 64 32Z"
            fill="none"
            stroke={c.artInk}
            strokeWidth={2.25}
          />
          <Path
            d="M64 90H176Q178 90 178 92V134Q178 136 176 136H64Q62 136 62 134V92Q62 90 64 90Z"
            fill={c.artShade}
          />
          <Path
            d="M64 90H176Q178 90 178 92V134Q178 136 176 136H64Q62 136 62 134V92Q62 90 64 90Z"
            fill="none"
            stroke={c.artInk}
            strokeWidth={2.25}
          />
          <Rect x={58} y={25} width={124} height={4} fill={c.artShine} rx={2} />
          <G transform="translate(150 136) rotate(18) scale(1)">
            <Path
              d="M2 -40H11Q13 -40 13 -38V-2Q13 0 11 0H2Q0 0 0 -2V-38Q0 -40 2 -40Z"
              fill={c.accent}
            />
            <Path
              d="M2 -40H11Q13 -40 13 -38V-2Q13 0 11 0H2Q0 0 0 -2V-38Q0 -40 2 -40Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.25}
            />
            <Rect x={0} y={-32} width={13} height={4} fill={c.gold} />
            <Rect x={0} y={-12} width={13} height={4} fill={c.gold} />
            <Path
              d="M2 -40H11Q13 -40 13 -38V-2Q13 0 11 0H2Q0 0 0 -2V-38Q0 -40 2 -40Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.25}
            />
          </G>
          <Line x1={176} y1={146} x2={182} y2={152} stroke={c.artInk} strokeWidth={2.25} />
          <Line x1={64} y1={146} x2={58} y2={152} stroke={c.artInk} strokeWidth={2.25} />
        </G>
      </Svg>
    </View>
  );
}
