// Generated by scripts/render-art.mjs from its drawing of B14; change the drawing there and rerun.
import { View } from 'react-native';
import Svg, { Circle, Ellipse, G, Line, Path, Rect } from 'react-native-svg';

import { usePalette } from '@/theme';

/**
 * B14: A flask, the corner of a circuit board, a gear and a graph.
 * Artboard 320 x 200; `width` scales it. Decorative (hidden from screen readers) unless
 * a `label` is given. Colours come from the palette, so one drawing serves light and dark.
 */
export function ExploreCollege({ width = 320, label }: { width?: number; label?: string }) {
  const c = usePalette();
  return (
    <View
      role={label ? 'img' : undefined}
      aria-label={label}
      aria-hidden={!label}
      importantForAccessibility={label ? 'yes' : 'no-hide-descendants'}
    >
      <Svg width={width} height={width * 0.625} viewBox={'0 0 320 200'}>
        <G strokeLinecap="round" strokeLinejoin="round">
          <Circle cx={160} cy={104} r={92} fill={c.accentSoft} />
          <Ellipse cx={160} cy={183} rx={130} ry={4} fill={c.artShade} />
          <G transform="translate(92 84) scale(1)">
            <Path
              d="M28.8 0L35.9 2.71L34.69 9.61L27.1 9.76L23.3 16.93L27.45 23.29L22.42 28.17L16.19 23.82L8.9 27.39L8.51 34.98L1.58 35.97L-0.9 28.79L-8.9 27.39L-13.67 33.3L-19.86 30.03L-17.65 22.76L-23.3 16.93L-30.64 18.91L-33.72 12.62L-27.66 8.03L-28.8 0L-35.9 -2.71L-34.69 -9.61L-27.1 -9.76L-23.3 -16.93L-27.45 -23.29L-22.42 -28.17L-16.19 -23.82L-8.9 -27.39L-8.51 -34.98L-1.58 -35.97L0.9 -28.79L8.9 -27.39L13.67 -33.3L19.86 -30.03L17.65 -22.76L23.3 -16.93L30.64 -18.91L33.72 -12.62L27.66 -8.03Z"
              fill={c.artGrey}
            />
            <Path
              d="M28.8 0L35.9 2.71L34.69 9.61L27.1 9.76L23.3 16.93L27.45 23.29L22.42 28.17L16.19 23.82L8.9 27.39L8.51 34.98L1.58 35.97L-0.9 28.79L-8.9 27.39L-13.67 33.3L-19.86 30.03L-17.65 22.76L-23.3 16.93L-30.64 18.91L-33.72 12.62L-27.66 8.03L-28.8 0L-35.9 -2.71L-34.69 -9.61L-27.1 -9.76L-23.3 -16.93L-27.45 -23.29L-22.42 -28.17L-16.19 -23.82L-8.9 -27.39L-8.51 -34.98L-1.58 -35.97L0.9 -28.79L8.9 -27.39L13.67 -33.3L19.86 -30.03L17.65 -22.76L23.3 -16.93L30.64 -18.91L33.72 -12.62L27.66 -8.03Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.5}
            />
            <Circle cx={0} cy={0} r={18} fill={c.artShade} />
            <Circle cx={0} cy={0} r={18} fill="none" stroke={c.artInk} strokeWidth={2} />
            <Circle cx={0} cy={0} r={7.2} fill={c.artPaper} stroke={c.artInk} strokeWidth={2.5} />
          </G>
          <G transform="translate(28 124) scale(1)">
            <Path
              d="M5.8 0H118.2Q124 0 124 5.8V52.2Q124 58 118.2 58H5.8Q0 58 0 52.2V5.8Q0 0 5.8 0Z"
              fill={c.accent}
            />
            <Path
              d="M5.8 0H118.2Q124 0 124 5.8V52.2Q124 58 118.2 58H5.8Q0 58 0 52.2V5.8Q0 0 5.8 0Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.5}
            />
            <Path
              d="M12.4 16.240000000000002H49.6L62 23.200000000000003"
              fill="none"
              stroke={c.gold}
              strokeWidth={2.75}
            />
            <Path
              d="M12.4 47.559999999999995H37.199999999999996L49.6 40.599999999999994"
              fill="none"
              stroke={c.gold}
              strokeWidth={2.75}
            />
            <Path
              d="M101.67999999999999 8.120000000000001V17.4"
              fill="none"
              stroke={c.gold}
              strokeWidth={2.75}
            />
            <Path
              d="M111.60000000000001 34.8H96.72"
              fill="none"
              stroke={c.gold}
              strokeWidth={2.75}
            />
            <Circle cx={12.4} cy={16.24} r={4} fill={c.gold} stroke={c.artInk} strokeWidth={1.5} />
            <Circle cx={12.4} cy={47.56} r={4} fill={c.gold} stroke={c.artInk} strokeWidth={1.5} />
            <Circle cx={101.68} cy={8.12} r={4} fill={c.gold} stroke={c.artInk} strokeWidth={1.5} />
            <Circle cx={111.6} cy={34.8} r={4} fill={c.gold} stroke={c.artInk} strokeWidth={1.5} />
            <Line
              x1={50.84}
              y1={25.98}
              x2={57.04}
              y2={25.98}
              stroke={c.artGrey}
              strokeWidth={2.75}
            />
            <Line
              x1={96.72}
              y1={25.98}
              x2={102.92}
              y2={25.98}
              stroke={c.artGrey}
              strokeWidth={2.75}
            />
            <Line
              x1={50.84}
              y1={32.48}
              x2={57.04}
              y2={32.48}
              stroke={c.artGrey}
              strokeWidth={2.75}
            />
            <Line
              x1={96.72}
              y1={32.48}
              x2={102.92}
              y2={32.48}
              stroke={c.artGrey}
              strokeWidth={2.75}
            />
            <Line
              x1={50.84}
              y1={38.98}
              x2={57.04}
              y2={38.98}
              stroke={c.artGrey}
              strokeWidth={2.75}
            />
            <Line
              x1={96.72}
              y1={38.98}
              x2={102.92}
              y2={38.98}
              stroke={c.artGrey}
              strokeWidth={2.75}
            />
            <Path
              d="M59.04 20.88H94.72Q96.72 20.88 96.72 22.88V42.08Q96.72 44.08 94.72 44.08H59.04Q57.04 44.08 57.04 42.08V22.88Q57.04 20.88 59.04 20.88Z"
              fill={c.artInk}
              stroke={c.artInk}
              strokeWidth={2.5}
            />
            <Circle cx={64.98} cy={25.52} r={1.75} fill={c.artGrey} />
          </G>
          <G transform="translate(206 182) scale(1)">
            <Path
              d="M7.36 -112H84.64Q92 -112 92 -104.64V-7.36Q92 0 84.64 0H7.36Q0 0 0 -7.36V-104.64Q0 -112 7.36 -112Z"
              fill={c.artPaper}
              stroke={c.artInk}
              strokeWidth={2.5}
            />
            <Line
              x1={31.83}
              y1={-17.92}
              x2={31.83}
              y2={-101.25}
              stroke={c.artGrey}
              strokeWidth={1.5}
            />
            <Line
              x1={14.72}
              y1={-38.75}
              x2={83.17}
              y2={-38.75}
              stroke={c.artGrey}
              strokeWidth={1.5}
            />
            <Line
              x1={48.94}
              y1={-17.92}
              x2={48.94}
              y2={-101.25}
              stroke={c.artGrey}
              strokeWidth={1.5}
            />
            <Line
              x1={14.72}
              y1={-59.58}
              x2={83.17}
              y2={-59.58}
              stroke={c.artGrey}
              strokeWidth={1.5}
            />
            <Line
              x1={66.06}
              y1={-17.92}
              x2={66.06}
              y2={-101.25}
              stroke={c.artGrey}
              strokeWidth={1.5}
            />
            <Line
              x1={14.72}
              y1={-80.42}
              x2={83.17}
              y2={-80.42}
              stroke={c.artGrey}
              strokeWidth={1.5}
            />
            <Line
              x1={14.72}
              y1={-17.92}
              x2={14.72}
              y2={-105.73}
              stroke={c.artInk}
              strokeWidth={2.5}
            />
            <Line
              x1={14.72}
              y1={-17.92}
              x2={86.85}
              y2={-17.92}
              stroke={c.artInk}
              strokeWidth={2.5}
            />
            <Path
              d="M14.72 -59.58L17.57 -66.92L20.42 -73.75L23.28 -79.62L26.13 -84.12L28.98 -86.95L31.83 -87.92L34.68 -86.95L37.54 -84.12L40.39 -79.62L43.24 -73.75L46.09 -66.92L48.94 -59.58L51.8 -52.25L54.65 -45.42L57.5 -39.55L60.35 -35.05L63.2 -32.22L66.06 -31.25L68.91 -32.22L71.76 -35.05L74.61 -39.55L77.46 -45.42L80.32 -52.25L83.17 -59.58"
              fill="none"
              stroke={c.accent}
              strokeWidth={3.5}
            />
            <Circle
              cx={31.83}
              cy={-87.92}
              r={4.5}
              fill={c.gold}
              stroke={c.artInk}
              strokeWidth={2}
            />
          </G>
          <G transform="translate(168 182) scale(1)">
            <Path
              d="M-10 -96L-10 -62L-33 -9Q-36 0 -26 0L26 0Q36 0 33 -9L10 -62L10 -96Z"
              fill={c.accentSoft}
              fillOpacity={0.55}
            />
            <Path d="M-23.6 -32L-33 -9Q-36 0 -26 0L26 0Q36 0 33 -9L23.6 -32Z" fill={c.artTeal} />
            <Path d="M-23.6 -32H23.6L21 -26H-21Z" fill={c.artShine} />
            <Line x1={-23.6} y1={-32} x2={23.6} y2={-32} stroke={c.artInk} strokeWidth={2} />
            <Circle
              cx={-8}
              cy={-14}
              r={3.2}
              fill={c.artShine}
              stroke={c.artInk}
              strokeWidth={1.25}
            />
            <Circle
              cx={6}
              cy={-20}
              r={2.2}
              fill={c.artShine}
              stroke={c.artInk}
              strokeWidth={1.25}
            />
            <Circle
              cx={12}
              cy={-9}
              r={2.6}
              fill={c.artShine}
              stroke={c.artInk}
              strokeWidth={1.25}
            />
            <Path d="M-5 -88V-66L-14 -45" fill="none" stroke={c.artShine} strokeWidth={4} />
            <Path
              d="M-10 -96L-10 -62L-33 -9Q-36 0 -26 0L26 0Q36 0 33 -9L10 -62L10 -96"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.5}
            />
            <Rect
              x={-14}
              y={-102}
              width={28}
              height={7}
              fill={c.artPaper}
              stroke={c.artInk}
              strokeWidth={2.5}
              rx={3}
            />
          </G>
          <Path
            d="M46 45Q47.96 50.04 53 52Q47.96 53.96 46 59Q44.04 53.96 39 52Q44.04 50.04 46 45Z"
            fill={c.gold}
          />
          <Circle cx={290} cy={52} r={3.5} fill={c.accent} />
        </G>
      </Svg>
    </View>
  );
}
