// Generated by scripts/render-art.mjs from its drawing of B13; change the drawing there and rerun.
import { View } from 'react-native';
import Svg, { Circle, Ellipse, G, Line, Path, Rect } from 'react-native-svg';

import { usePalette } from '@/theme';

/**
 * B13: A stack of school things: a ruler, a ten-frame with seven counters, a pencil on top, and a small plant.
 * Artboard 320 x 200; `width` scales it. Decorative (hidden from screen readers) unless
 * a `label` is given. Colours come from the palette, so one drawing serves light and dark.
 */
export function ExploreK12({ width = 320, label }: { width?: number; label?: string }) {
  const c = usePalette();
  return (
    <View
      role={label ? 'img' : undefined}
      aria-label={label}
      aria-hidden={!label}
      importantForAccessibility={label ? 'yes' : 'no-hide-descendants'}
    >
      <Svg width={width} height={width * 0.625} viewBox={'0 0 320 200'}>
        <G strokeLinecap="round" strokeLinejoin="round">
          <Circle cx={160} cy={104} r={92} fill={c.accentSoft} />
          <Ellipse cx={160} cy={183} rx={130} ry={4} fill={c.artShade} />
          <G transform="translate(30 182) scale(1)">
            <Path
              d="M2.38 -17H197.62Q200 -17 200 -14.62V-2.38Q200 0 197.62 0H2.38Q0 0 0 -2.38V-14.62Q0 -17 2.38 -17Z"
              fill={c.gold}
            />
            <Rect x={0} y={-5.78} width={200} height={5.78} fill={c.artShade} />
            <Line x1={10} y1={-17} x2={10} y2={-11.9} stroke={c.artInk} strokeWidth={1.5} />
            <Line x1={20} y1={-17} x2={20} y2={-11.9} stroke={c.artInk} strokeWidth={1.5} />
            <Line x1={30} y1={-17} x2={30} y2={-11.9} stroke={c.artInk} strokeWidth={1.5} />
            <Line x1={40} y1={-17} x2={40} y2={-11.9} stroke={c.artInk} strokeWidth={1.5} />
            <Line x1={50} y1={-17} x2={50} y2={-7.65} stroke={c.artInk} strokeWidth={1.5} />
            <Line x1={60} y1={-17} x2={60} y2={-11.9} stroke={c.artInk} strokeWidth={1.5} />
            <Line x1={70} y1={-17} x2={70} y2={-11.9} stroke={c.artInk} strokeWidth={1.5} />
            <Line x1={80} y1={-17} x2={80} y2={-11.9} stroke={c.artInk} strokeWidth={1.5} />
            <Line x1={90} y1={-17} x2={90} y2={-11.9} stroke={c.artInk} strokeWidth={1.5} />
            <Line x1={100} y1={-17} x2={100} y2={-7.65} stroke={c.artInk} strokeWidth={1.5} />
            <Line x1={110} y1={-17} x2={110} y2={-11.9} stroke={c.artInk} strokeWidth={1.5} />
            <Line x1={120} y1={-17} x2={120} y2={-11.9} stroke={c.artInk} strokeWidth={1.5} />
            <Line x1={130} y1={-17} x2={130} y2={-11.9} stroke={c.artInk} strokeWidth={1.5} />
            <Line x1={140} y1={-17} x2={140} y2={-11.9} stroke={c.artInk} strokeWidth={1.5} />
            <Line x1={150} y1={-17} x2={150} y2={-7.65} stroke={c.artInk} strokeWidth={1.5} />
            <Line x1={160} y1={-17} x2={160} y2={-11.9} stroke={c.artInk} strokeWidth={1.5} />
            <Line x1={170} y1={-17} x2={170} y2={-11.9} stroke={c.artInk} strokeWidth={1.5} />
            <Line x1={180} y1={-17} x2={180} y2={-11.9} stroke={c.artInk} strokeWidth={1.5} />
            <Line x1={190} y1={-17} x2={190} y2={-11.9} stroke={c.artInk} strokeWidth={1.5} />
            <Path
              d="M2.38 -17H197.62Q200 -17 200 -14.62V-2.38Q200 0 197.62 0H2.38Q0 0 0 -2.38V-14.62Q0 -17 2.38 -17Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.5}
            />
          </G>
          <G transform="translate(50 165) scale(1)">
            <Path
              d="M5.2 -66.56H139.36Q144.56 -66.56 144.56 -61.36V-5.2Q144.56 0 139.36 0H5.2Q0 0 0 -5.2V-61.36Q0 -66.56 5.2 -66.56Z"
              fill={c.artPaper}
              stroke={c.artInk}
              strokeWidth={2.5}
            />
            <Rect
              x={7.28}
              y={-59.28}
              width={26}
              height={26}
              fill="none"
              stroke={c.artInk}
              strokeWidth={2}
            />
            <Circle
              cx={20.28}
              cy={-46.28}
              r={8.32}
              fill={c.accent}
              stroke={c.artInk}
              strokeWidth={2}
            />
            <Circle cx={18.2} cy={-48.88} r={2.34} fill={c.artShine} />
            <Rect
              x={33.28}
              y={-59.28}
              width={26}
              height={26}
              fill="none"
              stroke={c.artInk}
              strokeWidth={2}
            />
            <Circle
              cx={46.28}
              cy={-46.28}
              r={8.32}
              fill={c.accent}
              stroke={c.artInk}
              strokeWidth={2}
            />
            <Circle cx={44.2} cy={-48.88} r={2.34} fill={c.artShine} />
            <Rect
              x={59.28}
              y={-59.28}
              width={26}
              height={26}
              fill="none"
              stroke={c.artInk}
              strokeWidth={2}
            />
            <Circle
              cx={72.28}
              cy={-46.28}
              r={8.32}
              fill={c.accent}
              stroke={c.artInk}
              strokeWidth={2}
            />
            <Circle cx={70.2} cy={-48.88} r={2.34} fill={c.artShine} />
            <Rect
              x={85.28}
              y={-59.28}
              width={26}
              height={26}
              fill="none"
              stroke={c.artInk}
              strokeWidth={2}
            />
            <Circle
              cx={98.28}
              cy={-46.28}
              r={8.32}
              fill={c.accent}
              stroke={c.artInk}
              strokeWidth={2}
            />
            <Circle cx={96.2} cy={-48.88} r={2.34} fill={c.artShine} />
            <Rect
              x={111.28}
              y={-59.28}
              width={26}
              height={26}
              fill="none"
              stroke={c.artInk}
              strokeWidth={2}
            />
            <Circle
              cx={124.28}
              cy={-46.28}
              r={8.32}
              fill={c.accent}
              stroke={c.artInk}
              strokeWidth={2}
            />
            <Circle cx={122.2} cy={-48.88} r={2.34} fill={c.artShine} />
            <Rect
              x={7.28}
              y={-33.28}
              width={26}
              height={26}
              fill="none"
              stroke={c.artInk}
              strokeWidth={2}
            />
            <Circle
              cx={20.28}
              cy={-20.28}
              r={8.32}
              fill={c.accent}
              stroke={c.artInk}
              strokeWidth={2}
            />
            <Circle cx={18.2} cy={-22.88} r={2.34} fill={c.artShine} />
            <Rect
              x={33.28}
              y={-33.28}
              width={26}
              height={26}
              fill="none"
              stroke={c.artInk}
              strokeWidth={2}
            />
            <Circle
              cx={46.28}
              cy={-20.28}
              r={8.32}
              fill={c.accent}
              stroke={c.artInk}
              strokeWidth={2}
            />
            <Circle cx={44.2} cy={-22.88} r={2.34} fill={c.artShine} />
            <Rect
              x={59.28}
              y={-33.28}
              width={26}
              height={26}
              fill="none"
              stroke={c.artInk}
              strokeWidth={2}
            />
            <Rect
              x={85.28}
              y={-33.28}
              width={26}
              height={26}
              fill="none"
              stroke={c.artInk}
              strokeWidth={2}
            />
            <Rect
              x={111.28}
              y={-33.28}
              width={26}
              height={26}
              fill="none"
              stroke={c.artInk}
              strokeWidth={2}
            />
          </G>
          <G transform="translate(50 104) rotate(-6) scale(1)">
            <Path
              d="M4.2 -7H13.2Q17.4 -7 17.4 -2.8V2.8Q17.4 7 13.2 7H4.2Q0 7 0 2.8V-2.8Q0 -7 4.2 -7Z"
              fill={c.artRose}
            />
            <Path
              d="M4.2 -7H13.2Q17.4 -7 17.4 -2.8V2.8Q17.4 7 13.2 7H4.2Q0 7 0 2.8V-2.8Q0 -7 4.2 -7Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.5}
            />
            <Path d="M15.4 -7L25.2 -7L25.2 7L15.4 7Z" fill={c.artGrey} />
            <Path d="M15.4 -7L25.2 -7L25.2 7L15.4 7Z" fill={c.artShine} />
            <Path
              d="M15.4 -7L25.2 -7L25.2 7L15.4 7Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.5}
            />
            <Line x1={20.3} y1={-7} x2={20.3} y2={7} stroke={c.artInk} strokeWidth={1.5} />
            <Path d="M25.2 -7L144.2 -7L144.2 7L25.2 7Z" fill={c.accent} />
            <Path
              d="M25.2 -7L144.2 -7L144.2 7L25.2 7Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.5}
            />
            <Path d="M25.2 -1.05L144.2 -1.05L144.2 7L25.2 7Z" fill={c.artShade} />
            <Path
              d="M25.2 -7L144.2 -7L144.2 7L25.2 7Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.5}
            />
            <Path d="M144.2 -7L168 0L144.2 7Z" fill={c.artWood} />
            <Path d="M144.2 -7L168 0L144.2 7Z" fill="none" stroke={c.artInk} strokeWidth={2.5} />
            <Path d="M159.43 -2.52L168 0L159.43 2.52Z" fill={c.artInk} />
          </G>
          <G transform="translate(262 182) scale(1.2)">
            <Path d="M0 -30Q-2 -48 0 -64" fill="none" stroke={c.artInk} strokeWidth={2.08} />
            <Path d="M0 -40Q-15.81 -40.08 -21.3 -54.91Q-5.49 -54.83 0 -40Z" fill={c.artGreen} />
            <Path
              d="M0 -40Q-15.81 -40.08 -21.3 -54.91Q-5.49 -54.83 0 -40Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.08}
            />
            <Path d="M0 -48Q4.05 -61.84 18.39 -63.43Q14.33 -49.59 0 -48Z" fill={c.artGreen} />
            <Path d="M0 -48Q4.05 -61.84 18.39 -63.43Q14.33 -49.59 0 -48Z" fill={c.artShade} />
            <Path
              d="M0 -48Q4.05 -61.84 18.39 -63.43Q14.33 -49.59 0 -48Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.08}
            />
            <Path d="M0 -60Q-10.34 -67.94 -7.52 -80.67Q2.82 -72.73 0 -60Z" fill={c.artGreen} />
            <Path
              d="M0 -60Q-10.34 -67.94 -7.52 -80.67Q2.82 -72.73 0 -60Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.08}
            />
            <Path d="M0 -62Q-2.56 -72.51 6.16 -78.91Q8.72 -68.41 0 -62Z" fill={c.artGreen} />
            <Path d="M0 -62Q-2.56 -72.51 6.16 -78.91Q8.72 -68.41 0 -62Z" fill={c.artShade} />
            <Path
              d="M0 -62Q-2.56 -72.51 6.16 -78.91Q8.72 -68.41 0 -62Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.08}
            />
            <Path d="M-17 -26L-13 0H13L17 -26Z" fill={c.accent} />
            <Path d="M-17 -26L-13 0H13L17 -26Z" fill="none" stroke={c.artInk} strokeWidth={2.08} />
            <Path d="M2 -26L4 0H13L17 -26Z" fill={c.artShade} />
            <Path d="M-17 -26L-13 0H13L17 -26Z" fill="none" stroke={c.artInk} strokeWidth={2.08} />
            <Path
              d="M-18.5 -33H18.5Q21 -33 21 -30.5V-26.5Q21 -24 18.5 -24H-18.5Q-21 -24 -21 -26.5V-30.5Q-21 -33 -18.5 -33Z"
              fill={c.accent}
            />
            <Path
              d="M-18.5 -33H18.5Q21 -33 21 -30.5V-26.5Q21 -24 18.5 -24H-18.5Q-21 -24 -21 -26.5V-30.5Q-21 -33 -18.5 -33Z"
              fill={c.artShine}
            />
            <Path
              d="M-18.5 -33H18.5Q21 -33 21 -30.5V-26.5Q21 -24 18.5 -24H-18.5Q-21 -24 -21 -26.5V-30.5Q-21 -33 -18.5 -33Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.08}
            />
          </G>
          <Path
            d="M262 39Q263.96 44.04 269 46Q263.96 47.96 262 53Q260.04 47.96 255 46Q260.04 44.04 262 39Z"
            fill={c.gold}
          />
          <Circle cx={40} cy={66} r={3.5} fill={c.accent} />
        </G>
      </Svg>
    </View>
  );
}
