// Generated by scripts/render-art.mjs from its drawing of B12; change the drawing there and rerun.
import { View } from 'react-native';
import Svg, { Circle, Ellipse, G, Line, Path, Rect } from 'react-native-svg';

import { usePalette } from '@/theme';

const CROP = { w: 480, h: 160 };

/**
 * B12: A desk of learning objects rising from simple to advanced, left to right: counting blocks, a fraction bar, a protractor, a beaker and a graph with a curve.
 * Artboard 480 x 320; `width` scales it. Decorative (hidden from screen readers) unless
 * a `label` is given. Colours come from the palette, so one drawing serves light and dark.
 * `band` crops it to the 480 x 160 strip of objects (shown at 360 x 120 on
 * phones).
 */
export function HomeHero({
  band = false,
  width = band ? CROP.w : 480,
  label,
}: {
  width?: number;
  label?: string;
  band?: boolean;
}) {
  const c = usePalette();
  return (
    <View
      role={label ? 'img' : undefined}
      aria-label={label}
      aria-hidden={!label}
      importantForAccessibility={label ? 'yes' : 'no-hide-descendants'}
    >
      <Svg
        width={width}
        height={width * (band ? CROP.h / CROP.w : 0.6666666666666666)}
        viewBox={band ? '0 128 480 160' : '0 0 480 320'}
      >
        <G strokeLinecap="round" strokeLinejoin="round">
          <Circle cx={250} cy={170} r={150} fill={c.accentSoft} />
          <Path
            d="M70 196Q240 70 420 112"
            fill="none"
            stroke={c.accent}
            strokeWidth={3}
            strokeDasharray="2 10"
          />
          <Path d="M408 100L424 112L406 122" fill="none" stroke={c.accent} strokeWidth={3} />
          <Path
            d="M92 102Q94.8 109.2 102 112Q94.8 114.8 92 122Q89.2 114.8 82 112Q89.2 109.2 92 102Z"
            fill={c.gold}
          />
          <Path
            d="M300 59Q301.96 64.04 307 66Q301.96 67.96 300 73Q298.04 67.96 293 66Q298.04 64.04 300 59Z"
            fill={c.gold}
          />
          <Circle cx={176} cy={92} r={4} fill={c.accent} />
          <Circle cx={360} cy={76} r={3} fill={c.accent} />
          <Path
            d="M14 262H466Q472 262 472 268V278Q472 284 466 284H14Q8 284 8 278V268Q8 262 14 262Z"
            fill={c.artGrey}
            stroke={c.artInk}
            strokeWidth={3}
          />
          <Path d="M8 262H472V269H8Z" fill={c.artPaper} stroke={c.artInk} strokeWidth={3} />
          <Ellipse cx={64} cy={262} rx={52} ry={3} fill={c.artShade} />
          <Path d="M52 234L60.4 225.6L60.4 253.6L52 262Z" fill={c.accent} />
          <Path d="M52 234L60.4 225.6L60.4 253.6L52 262Z" fill={c.artShade} />
          <Path
            d="M52 234L60.4 225.6L60.4 253.6L52 262Z"
            fill="none"
            stroke={c.artInk}
            strokeWidth={3}
          />
          <Path d="M24 234L32.4 225.6L60.4 225.6L52 234Z" fill={c.accent} />
          <Path d="M24 234L32.4 225.6L60.4 225.6L52 234Z" fill={c.artShine} />
          <Path
            d="M24 234L32.4 225.6L60.4 225.6L52 234Z"
            fill="none"
            stroke={c.artInk}
            strokeWidth={3}
          />
          <Path
            d="M26.24 234H49.76Q52 234 52 236.24V259.76Q52 262 49.76 262H26.24Q24 262 24 259.76V236.24Q24 234 26.24 234Z"
            fill={c.accent}
          />
          <Path
            d="M26.24 234H49.76Q52 234 52 236.24V259.76Q52 262 49.76 262H26.24Q24 262 24 259.76V236.24Q24 234 26.24 234Z"
            fill="none"
            stroke={c.artInk}
            strokeWidth={3}
          />
          <Path d="M80 234L88.4 225.6L88.4 253.6L80 262Z" fill={c.gold} />
          <Path d="M80 234L88.4 225.6L88.4 253.6L80 262Z" fill={c.artShade} />
          <Path
            d="M80 234L88.4 225.6L88.4 253.6L80 262Z"
            fill="none"
            stroke={c.artInk}
            strokeWidth={3}
          />
          <Path d="M52 234L60.4 225.6L88.4 225.6L80 234Z" fill={c.gold} />
          <Path d="M52 234L60.4 225.6L88.4 225.6L80 234Z" fill={c.artShine} />
          <Path
            d="M52 234L60.4 225.6L88.4 225.6L80 234Z"
            fill="none"
            stroke={c.artInk}
            strokeWidth={3}
          />
          <Path
            d="M54.24 234H77.76Q80 234 80 236.24V259.76Q80 262 77.76 262H54.24Q52 262 52 259.76V236.24Q52 234 54.24 234Z"
            fill={c.gold}
          />
          <Path
            d="M54.24 234H77.76Q80 234 80 236.24V259.76Q80 262 77.76 262H54.24Q52 262 52 259.76V236.24Q52 234 54.24 234Z"
            fill="none"
            stroke={c.artInk}
            strokeWidth={3}
          />
          <Path d="M66 206L74.4 197.6L74.4 225.6L66 234Z" fill={c.artTeal} />
          <Path d="M66 206L74.4 197.6L74.4 225.6L66 234Z" fill={c.artShade} />
          <Path
            d="M66 206L74.4 197.6L74.4 225.6L66 234Z"
            fill="none"
            stroke={c.artInk}
            strokeWidth={3}
          />
          <Path d="M38 206L46.4 197.6L74.4 197.6L66 206Z" fill={c.artTeal} />
          <Path d="M38 206L46.4 197.6L74.4 197.6L66 206Z" fill={c.artShine} />
          <Path
            d="M38 206L46.4 197.6L74.4 197.6L66 206Z"
            fill="none"
            stroke={c.artInk}
            strokeWidth={3}
          />
          <Path
            d="M40.24 206H63.76Q66 206 66 208.24V231.76Q66 234 63.76 234H40.24Q38 234 38 231.76V208.24Q38 206 40.24 206Z"
            fill={c.artTeal}
          />
          <Path
            d="M40.24 206H63.76Q66 206 66 208.24V231.76Q66 234 63.76 234H40.24Q38 234 38 231.76V208.24Q38 206 40.24 206Z"
            fill="none"
            stroke={c.artInk}
            strokeWidth={3}
          />
          <Ellipse cx={156} cy={262} rx={58} ry={3} fill={c.artShade} />
          <G transform="translate(100 262) rotate(-21) scale(1)">
            <Rect x={0} y={-22} width={29} height={22} fill={c.accent} />
            <Rect x={29} y={-22} width={29} height={22} fill={c.accent} />
            <Rect x={58} y={-22} width={29} height={22} fill={c.accent} />
            <Rect x={87} y={-22} width={29} height={22} fill={c.artPaper} />
            <Rect x={0} y={-19.36} width={116} height={4.84} fill={c.artShine} />
            <Line x1={29} y1={-22} x2={29} y2={0} stroke={c.artInk} strokeWidth={2.4} />
            <Line x1={58} y1={-22} x2={58} y2={0} stroke={c.artInk} strokeWidth={2.4} />
            <Line x1={87} y1={-22} x2={87} y2={0} stroke={c.artInk} strokeWidth={2.4} />
            <Rect
              x={0}
              y={-22}
              width={116}
              height={22}
              fill="none"
              stroke={c.artInk}
              strokeWidth={3}
              rx={2.64}
            />
          </G>
          <G transform="translate(236 262) scale(1)">
            <Path d="M-50 0A50 50 0 0 1 50 0Z" fill={c.artPaper} fillOpacity={0.9} />
            <Line x1={43.33} y1={-7.64} x2={47.76} y2={-8.42} stroke={c.artInk} strokeWidth={1.8} />
            <Line
              x1={41.35}
              y1={-15.05}
              x2={45.58}
              y2={-16.59}
              stroke={c.artInk}
              strokeWidth={1.8}
            />
            <Line x1={35.51} y1={-20.5} x2={42} y2={-24.25} stroke={c.artInk} strokeWidth={1.8} />
            <Line
              x1={33.71}
              y1={-28.28}
              x2={37.15}
              y2={-31.18}
              stroke={c.artInk}
              strokeWidth={1.8}
            />
            <Line
              x1={28.28}
              y1={-33.71}
              x2={31.18}
              y2={-37.15}
              stroke={c.artInk}
              strokeWidth={1.8}
            />
            <Line x1={20.5} y1={-35.51} x2={24.25} y2={-42} stroke={c.artInk} strokeWidth={1.8} />
            <Line
              x1={15.05}
              y1={-41.35}
              x2={16.59}
              y2={-45.58}
              stroke={c.artInk}
              strokeWidth={1.8}
            />
            <Line x1={7.64} y1={-43.33} x2={8.42} y2={-47.76} stroke={c.artInk} strokeWidth={1.8} />
            <Line x1={0} y1={-37} x2={0} y2={-48.5} stroke={c.artInk} strokeWidth={1.8} />
            <Line
              x1={-7.64}
              y1={-43.33}
              x2={-8.42}
              y2={-47.76}
              stroke={c.artInk}
              strokeWidth={1.8}
            />
            <Line
              x1={-15.05}
              y1={-41.35}
              x2={-16.59}
              y2={-45.58}
              stroke={c.artInk}
              strokeWidth={1.8}
            />
            <Line x1={-20.5} y1={-35.51} x2={-24.25} y2={-42} stroke={c.artInk} strokeWidth={1.8} />
            <Line
              x1={-28.28}
              y1={-33.71}
              x2={-31.18}
              y2={-37.15}
              stroke={c.artInk}
              strokeWidth={1.8}
            />
            <Line
              x1={-33.71}
              y1={-28.28}
              x2={-37.15}
              y2={-31.18}
              stroke={c.artInk}
              strokeWidth={1.8}
            />
            <Line x1={-35.51} y1={-20.5} x2={-42} y2={-24.25} stroke={c.artInk} strokeWidth={1.8} />
            <Line
              x1={-41.35}
              y1={-15.05}
              x2={-45.58}
              y2={-16.59}
              stroke={c.artInk}
              strokeWidth={1.8}
            />
            <Line
              x1={-43.33}
              y1={-7.64}
              x2={-47.76}
              y2={-8.42}
              stroke={c.artInk}
              strokeWidth={1.8}
            />
            <Path d="M-17 0A17 17 0 0 1 17 0" fill="none" stroke={c.artInk} strokeWidth={2.4} />
            <Path d="M-50 0A50 50 0 0 1 50 0Z" fill="none" stroke={c.artInk} strokeWidth={3} />
            <Line x1={0} y1={0} x2={0} y2={-8} stroke={c.artInk} strokeWidth={2.4} />
          </G>
          <Ellipse cx={326} cy={262} rx={34} ry={3} fill={c.artShade} />
          <G transform="translate(324 262) scale(1.05)">
            <Path
              d="M-30 -76V-6Q-30 0 -24 0H24Q30 0 30 -6V-76Z"
              fill={c.accentSoft}
              fillOpacity={0.55}
            />
            <Path d="M-30 -31.92H30V-6Q30 0 24 0H-24Q-30 0 -30 -6Z" fill={c.artTeal} />
            <Path d="M-30 -31.92H30V-25.92H-30Z" fill={c.artShine} />
            <Line x1={-30} y1={-31.92} x2={30} y2={-31.92} stroke={c.artInk} strokeWidth={2.29} />
            <Rect x={-24} y={-68} width={5} height={58} fill={c.artShine} rx={2.5} />
            <Line x1={16} y1={-16} x2={28} y2={-16} stroke={c.artInk} strokeWidth={1.71} />
            <Line x1={20} y1={-30} x2={28} y2={-30} stroke={c.artInk} strokeWidth={1.71} />
            <Line x1={16} y1={-44} x2={28} y2={-44} stroke={c.artInk} strokeWidth={1.71} />
            <Line x1={20} y1={-58} x2={28} y2={-58} stroke={c.artInk} strokeWidth={1.71} />
            <Path
              d="M-30 -76V-6Q-30 0 -24 0H24Q30 0 30 -6V-76"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.86}
            />
            <Path d="M-36 -80Q-30 -79 -30 -74" fill="none" stroke={c.artInk} strokeWidth={2.86} />
            <Path d="M30 -74Q30 -79 34 -80" fill="none" stroke={c.artInk} strokeWidth={2.86} />
          </G>
          <Line x1={398} y1={262} x2={410} y2={220} stroke={c.artInk} strokeWidth={3} />
          <Line x1={452} y1={262} x2={440} y2={220} stroke={c.artInk} strokeWidth={3} />
          <G transform="translate(376 228) scale(1)">
            <Path
              d="M7.2 -92H82.8Q90 -92 90 -84.8V-7.2Q90 0 82.8 0H7.2Q0 0 0 -7.2V-84.8Q0 -92 7.2 -92Z"
              fill={c.artPaper}
              stroke={c.artInk}
              strokeWidth={3}
            />
            <Line
              x1={31.14}
              y1={-14.72}
              x2={31.14}
              y2={-83.17}
              stroke={c.artGrey}
              strokeWidth={1.8}
            />
            <Line
              x1={14.4}
              y1={-31.83}
              x2={81.36}
              y2={-31.83}
              stroke={c.artGrey}
              strokeWidth={1.8}
            />
            <Line
              x1={47.88}
              y1={-14.72}
              x2={47.88}
              y2={-83.17}
              stroke={c.artGrey}
              strokeWidth={1.8}
            />
            <Line
              x1={14.4}
              y1={-48.94}
              x2={81.36}
              y2={-48.94}
              stroke={c.artGrey}
              strokeWidth={1.8}
            />
            <Line
              x1={64.62}
              y1={-14.72}
              x2={64.62}
              y2={-83.17}
              stroke={c.artGrey}
              strokeWidth={1.8}
            />
            <Line
              x1={14.4}
              y1={-66.06}
              x2={81.36}
              y2={-66.06}
              stroke={c.artGrey}
              strokeWidth={1.8}
            />
            <Line x1={14.4} y1={-14.72} x2={14.4} y2={-86.85} stroke={c.artInk} strokeWidth={3} />
            <Line x1={14.4} y1={-14.72} x2={84.96} y2={-14.72} stroke={c.artInk} strokeWidth={3} />
            <Path
              d="M14.4 -20.2L17.19 -20.25L19.98 -20.43L22.77 -20.76L25.56 -21.26L28.35 -21.93L31.14 -22.79L33.93 -23.84L36.72 -25.08L39.51 -26.52L42.3 -28.18L45.09 -30.04L47.88 -32.11L50.67 -34.41L53.46 -36.92L56.25 -39.67L59.04 -42.64L61.83 -45.84L64.62 -49.28L67.41 -52.95L70.2 -56.86L72.99 -61.02L75.78 -65.41L78.57 -70.06L81.36 -74.95"
              fill="none"
              stroke={c.accent}
              strokeWidth={4.2}
            />
            <Circle
              cx={61.27}
              cy={-45.18}
              r={5.4}
              fill={c.gold}
              stroke={c.artInk}
              strokeWidth={2.4}
            />
          </G>
          <Rect
            x={372}
            y={226}
            width={98}
            height={7}
            fill={c.artWood}
            stroke={c.artInk}
            strokeWidth={3}
            rx={3}
          />
        </G>
      </Svg>
    </View>
  );
}
