// Generated by scripts/render-art.mjs from its drawing of B22; change the drawing there and rerun.
import { View } from 'react-native';
import Svg, { Circle, Ellipse, G, Path, Rect } from 'react-native-svg';

import { usePalette } from '@/theme';

/**
 * B22: A lesson card with a soft gold padlock badge.
 * Artboard 160 x 120; `width` scales it. Decorative (hidden from screen readers) unless
 * a `label` is given. Colours come from the palette, so one drawing serves light and dark.
 */
export function LockedLesson({ width = 160, label }: { width?: number; label?: string }) {
  const c = usePalette();
  return (
    <View
      role={label ? 'img' : undefined}
      aria-label={label}
      aria-hidden={!label}
      importantForAccessibility={label ? 'yes' : 'no-hide-descendants'}
    >
      <Svg width={width} height={width * 0.75} viewBox={'0 0 160 120'}>
        <G strokeLinecap="round" strokeLinejoin="round">
          <Ellipse cx={80} cy={60} rx={72} ry={54} fill={c.accentSoft} />
          <Path
            d="M36 22H112Q120 22 120 30V88Q120 96 112 96H36Q28 96 28 88V30Q28 22 36 22Z"
            fill={c.artShade}
          />
          <Path
            d="M32 18H108Q116 18 116 26V84Q116 92 108 92H32Q24 92 24 84V26Q24 18 32 18Z"
            fill={c.artPaper}
            stroke={c.artInk}
            strokeWidth={2}
          />
          <Path
            d="M36 26H104Q108 26 108 30V54Q108 58 104 58H36Q32 58 32 54V30Q32 26 36 26Z"
            fill={c.accentSoft}
            stroke={c.artInk}
            strokeWidth={1.5}
          />
          <Path d="M38 52Q54 50 62 42T98 32" fill="none" stroke={c.accent} strokeWidth={3} />
          <Rect x={32} y={66} width={56} height={5} fill={c.artGrey} rx={2.5} />
          <Rect x={32} y={77} width={40} height={5} fill={c.artGrey} rx={2.5} />
          <Circle cx={116} cy={86} r={21} fill={c.gold} stroke={c.card} strokeWidth={4} />
          <Circle cx={116} cy={86} r={19} fill="none" stroke={c.artInk} strokeWidth={2} />
          <G transform="translate(116 88) scale(1)">
            <Path
              d="M-5.1 -1.7V-7.14A5.1 5.1 0 0 1 5.1 -7.14V-1.7"
              fill="none"
              stroke={c.onGold}
              strokeWidth={2.72}
              strokeLinecap="round"
            />
            <Path
              d="M-6.12 -2.72H6.12Q8.5 -2.72 8.5 -0.34V8.16Q8.5 10.54 6.12 10.54H-6.12Q-8.5 10.54 -8.5 8.16V-0.34Q-8.5 -2.72 -6.12 -2.72Z"
              fill={c.onGold}
            />
            <Circle cx={0} cy={2.72} r={1.7} fill={c.gold} />
            <Rect x={-0.68} y={3.06} width={1.36} height={3.06} fill={c.gold} rx={0.51} />
          </G>
        </G>
      </Svg>
    </View>
  );
}
