// Generated by scripts/render-art.mjs from its drawing of B17; change the drawing there and rerun.
import { View } from 'react-native';
import Svg, { Circle, G, Path } from 'react-native-svg';

import { usePalette } from '@/theme';

/**
 * B17: A magnifier over a blank card.
 * Artboard 240 x 160; `width` scales it. Decorative (hidden from screen readers) unless
 * a `label` is given. Colours come from the palette, so one drawing serves light and dark.
 */
export function NoResults({ width = 240, label }: { width?: number; label?: string }) {
  const c = usePalette();
  return (
    <View
      role={label ? 'img' : undefined}
      aria-label={label}
      aria-hidden={!label}
      importantForAccessibility={label ? 'yes' : 'no-hide-descendants'}
    >
      <Svg width={width} height={width * 0.6666666666666666} viewBox={'0 0 240 160'}>
        <G strokeLinecap="round" strokeLinejoin="round">
          <Circle cx={120} cy={80} r={70} fill={c.accentSoft} />
          <G transform="translate(68 34) rotate(-5) scale(1)">
            <Path
              d="M15 6H93Q102 6 102 15V97Q102 106 93 106H15Q6 106 6 97V15Q6 6 15 6Z"
              fill={c.artShade}
            />
            <Path
              d="M9 0H87Q96 0 96 9V91Q96 100 87 100H9Q0 100 0 91V9Q0 0 9 0Z"
              fill={c.artPaper}
              stroke={c.artInk}
              strokeWidth={2.25}
            />
            <Path
              d="M19 14H77Q82 14 82 19V81Q82 86 77 86H19Q14 86 14 81V19Q14 14 19 14Z"
              fill="none"
              stroke={c.artGrey}
              strokeWidth={2}
              strokeDasharray="5 6"
            />
          </G>
          <G transform="translate(140 86) scale(1)">
            <Path d="M18.56 27.05L27.05 18.56L47.73 39.24L39.24 47.73Z" fill={c.accent} />
            <Path
              d="M18.56 27.05L27.05 18.56L47.73 39.24L39.24 47.73Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.25}
            />
            <Circle cx={0} cy={0} r={30} fill={c.artPaper} fillOpacity={0.55} />
            <Path
              d="M-18.6 -3.6A19.2 19.2 0 0 1 -3.6 -18.6"
              fill="none"
              stroke={c.artShine}
              strokeWidth={4.8}
            />
            <Circle cx={0} cy={0} r={30} fill="none" stroke={c.artGrey} strokeWidth={6} />
            <Circle cx={0} cy={0} r={33} fill="none" stroke={c.artInk} strokeWidth={2.25} />
            <Circle cx={0} cy={0} r={27} fill="none" stroke={c.artInk} strokeWidth={1.8} />
          </G>
          <Circle cx={48} cy={44} r={3} fill={c.accent} />
          <Path
            d="M196 32Q197.68 36.32 202 38Q197.68 39.68 196 44Q194.32 39.68 190 38Q194.32 36.32 196 32Z"
            fill={c.gold}
          />
        </G>
      </Svg>
    </View>
  );
}
