// Generated by scripts/render-art.mjs from its drawing of B21; change the drawing there and rerun.
import { View } from 'react-native';
import Svg, { Circle, G, Line, Path, Rect } from 'react-native-svg';

import { usePalette } from '@/theme';

/**
 * B21: A number line that breaks off into a gap, with a small signpost.
 * Artboard 320 x 200; `width` scales it. Decorative (hidden from screen readers) unless
 * a `label` is given. Colours come from the palette, so one drawing serves light and dark.
 */
export function NotFoundArt({ width = 320, label }: { width?: number; label?: string }) {
  const c = usePalette();
  return (
    <View
      role={label ? 'img' : undefined}
      aria-label={label}
      aria-hidden={!label}
      importantForAccessibility={label ? 'yes' : 'no-hide-descendants'}
    >
      <Svg width={width} height={width * 0.625} viewBox={'0 0 320 200'}>
        <G strokeLinecap="round" strokeLinejoin="round">
          <Circle cx={160} cy={100} r={92} fill={c.accentSoft} />
          <Path
            d="M24 150H204L210 157L203 164L208 172H24Z"
            fill={c.artGrey}
            stroke={c.artInk}
            strokeWidth={2.5}
          />
          <Path
            d="M254 150H300V172H252L258 164L251 157Z"
            fill={c.artGrey}
            stroke={c.artInk}
            strokeWidth={2.5}
          />
          <Rect
            x={166}
            y={48}
            width={8}
            height={102}
            fill={c.artWood}
            stroke={c.artInk}
            strokeWidth={2.5}
          />
          <Path
            d="M128 56H190L200 66L190 76H128Z"
            fill={c.artPaper}
            stroke={c.artInk}
            strokeWidth={2.5}
          />
          <Path
            d="M212 82H150L140 92L150 102H212Z"
            fill={c.accent}
            stroke={c.artInk}
            strokeWidth={2.5}
          />
          <Line x1={140} y1={66} x2={176} y2={66} stroke={c.artGrey} strokeWidth={3} />
          <Line x1={162} y1={92} x2={198} y2={92} stroke={c.artShine} strokeWidth={3} />
          <Line x1={30} y1={132} x2={200} y2={132} stroke={c.artInk} strokeWidth={3} />
          <Path d="M38 125L28 132L38 139" fill="none" stroke={c.artInk} strokeWidth={3} />
          <Line x1={52} y1={124} x2={52} y2={140} stroke={c.artInk} strokeWidth={2.5} />
          <Line x1={84} y1={124} x2={84} y2={140} stroke={c.artInk} strokeWidth={2.5} />
          <Line x1={116} y1={124} x2={116} y2={140} stroke={c.artInk} strokeWidth={2.5} />
          <Line x1={148} y1={124} x2={148} y2={140} stroke={c.artInk} strokeWidth={2.5} />
          <Line x1={180} y1={124} x2={180} y2={140} stroke={c.artInk} strokeWidth={2.5} />
          <Path
            d="M200 125L205 130L199 134L204 139"
            fill="none"
            stroke={c.artInk}
            strokeWidth={2}
          />
          <Circle cx={116} cy={132} r={7} fill={c.accent} stroke={c.artInk} strokeWidth={2.5} />
          <Line
            x1={264}
            y1={132}
            x2={292}
            y2={132}
            stroke={c.artGrey}
            strokeWidth={3}
            strokeDasharray="4 7"
          />
          <Path
            d="M70 62Q72.24 67.76 78 70Q72.24 72.24 70 78Q67.76 72.24 62 70Q67.76 67.76 70 62Z"
            fill={c.gold}
          />
          <Circle cx={282} cy={50} r={3.5} fill={c.accent} />
        </G>
      </Svg>
    </View>
  );
}
