// Generated by scripts/render-art.mjs from its drawing of B15; change the drawing there and rerun.
import { View } from 'react-native';
import Svg, { Circle, Ellipse, G, Line, Path, Rect } from 'react-native-svg';

import { usePalette } from '@/theme';

/**
 * B15: An open book from which three lesson pictures lift off (a number line with a slider knob, a beaker, a triangle with drag handles): pictures you can move.
 * Artboard 600 x 400; `width` scales it. Decorative (hidden from screen readers) unless
 * a `label` is given. Colours come from the palette, so one drawing serves light and dark.
 */
export function OnboardingWelcome({ width = 600, label }: { width?: number; label?: string }) {
  const c = usePalette();
  return (
    <View
      role={label ? 'img' : undefined}
      aria-label={label}
      aria-hidden={!label}
      importantForAccessibility={label ? 'yes' : 'no-hide-descendants'}
    >
      <Svg width={width} height={width * 0.6666666666666666} viewBox={'0 0 600 400'}>
        <G strokeLinecap="round" strokeLinejoin="round">
          <Circle cx={300} cy={200} r={178} fill={c.accentSoft} />
          <Line
            x1={206}
            y1={222}
            x2={194}
            y2={196}
            stroke={c.accent}
            strokeWidth={3.5}
            strokeDasharray="2 12"
          />
          <Line
            x1={300}
            y1={214}
            x2={310}
            y2={184}
            stroke={c.accent}
            strokeWidth={3.5}
            strokeDasharray="2 12"
          />
          <Line
            x1={394}
            y1={222}
            x2={420}
            y2={196}
            stroke={c.accent}
            strokeWidth={3.5}
            strokeDasharray="2 12"
          />
          <G transform="translate(62 156) rotate(-9) scale(1)">
            <Path
              d="M-2 -40H202Q214 -40 214 -28V10Q214 22 202 22H-2Q-14 22 -14 10V-28Q-14 -40 -2 -40Z"
              fill={c.artPaper}
              stroke={c.artInk}
              strokeWidth={3.5}
            />
            <Line x1={4} y1={0} x2={196} y2={0} stroke={c.artInk} strokeWidth={3.5} />
            <Path d="M188 -7L198 0L188 7" fill="none" stroke={c.artInk} strokeWidth={3.5} />
            <Line x1={20} y1={-8} x2={20} y2={8} stroke={c.artInk} strokeWidth={2.5} />
            <Line x1={56} y1={-8} x2={56} y2={8} stroke={c.artInk} strokeWidth={2.5} />
            <Line x1={92} y1={-8} x2={92} y2={8} stroke={c.artInk} strokeWidth={2.5} />
            <Line x1={128} y1={-8} x2={128} y2={8} stroke={c.artInk} strokeWidth={2.5} />
            <Line x1={164} y1={-8} x2={164} y2={8} stroke={c.artInk} strokeWidth={2.5} />
            <Line x1={20} y1={0} x2={128} y2={0} stroke={c.accent} strokeWidth={7} />
            <Circle cx={128} cy={0} r={11} fill={c.accent} stroke={c.artInk} strokeWidth={3.5} />
            <Circle cx={128} cy={0} r={4} fill={c.artPaper} />
            <Path
              d="M110 -26L100 -20L110 -14M146 -26L156 -20L146 -14"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.5}
            />
          </G>
          <G transform="translate(344 166) rotate(7) scale(1.3)">
            <Path
              d="M-30 -76V-6Q-30 0 -24 0H24Q30 0 30 -6V-76Z"
              fill={c.accentSoft}
              fillOpacity={0.55}
            />
            <Path d="M-30 -38H30V-6Q30 0 24 0H-24Q-30 0 -30 -6Z" fill={c.artTeal} />
            <Path d="M-30 -38H30V-32H-30Z" fill={c.artShine} />
            <Line x1={-30} y1={-38} x2={30} y2={-38} stroke={c.artInk} strokeWidth={2.15} />
            <Rect x={-24} y={-68} width={5} height={58} fill={c.artShine} rx={2.5} />
            <Line x1={16} y1={-16} x2={28} y2={-16} stroke={c.artInk} strokeWidth={1.62} />
            <Line x1={20} y1={-30} x2={28} y2={-30} stroke={c.artInk} strokeWidth={1.62} />
            <Line x1={16} y1={-44} x2={28} y2={-44} stroke={c.artInk} strokeWidth={1.62} />
            <Line x1={20} y1={-58} x2={28} y2={-58} stroke={c.artInk} strokeWidth={1.62} />
            <Path
              d="M-30 -76V-6Q-30 0 -24 0H24Q30 0 30 -6V-76"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.69}
            />
            <Path d="M-36 -80Q-30 -79 -30 -74" fill="none" stroke={c.artInk} strokeWidth={2.69} />
            <Path d="M30 -74Q30 -79 34 -80" fill="none" stroke={c.artInk} strokeWidth={2.69} />
          </G>
          <G transform="translate(452 214) rotate(8) scale(1)">
            <Path d="M0 0L104 0L0 -86Z" fill={c.gold} stroke={c.artInk} strokeWidth={3.5} />
            <Path d="M0 0L104 0L0 -86Z" fill={c.artShine} fillOpacity={0} />
            <Path d="M0 -16H16V0" fill="none" stroke={c.artInk} strokeWidth={2.5} />
            <Circle cx={0} cy={0} r={9} fill={c.artPaper} stroke={c.artInk} strokeWidth={3} />
            <Circle cx={104} cy={0} r={9} fill={c.artPaper} stroke={c.artInk} strokeWidth={3} />
            <Circle cx={0} cy={-86} r={9} fill={c.artPaper} stroke={c.artInk} strokeWidth={3} />
            <Circle cx={0} cy={-86} r={4} fill={c.accent} />
          </G>
          <Ellipse cx={300} cy={336} rx={196} ry={7} fill={c.artShade} />
          <G transform="translate(300 318) scale(1)">
            <Path
              d="M0 -3.28Q-89 -16.4 -186 -4.92V11.48Q-89 -1.64 0 13.12Q89 -1.64 186 11.48V-4.92Q89 -16.4 0 -3.28Z"
              fill={c.accent}
            />
            <Path
              d="M0 -3.28Q-89 -16.4 -186 -4.92V11.48Q-89 -1.64 0 13.12Q89 -1.64 186 11.48V-4.92Q89 -16.4 0 -3.28Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={3.5}
            />
            <Path
              d="M0 0C-44.5 -16.4 -106.8 -16.4 -178 -5.74V-77.08C-106.8 -88.56 -44.5 -88.56 0 -70.52Z"
              fill={c.artPaper}
            />
            <Path
              d="M0 0C-44.5 -16.4 -106.8 -16.4 -178 -5.74V-77.08C-106.8 -88.56 -44.5 -88.56 0 -70.52Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={3.5}
            />
            <Path
              d="M-21.36 -59.04C-53.4 -68.88 -106.8 -68.88 -153.08 -62.32"
              fill="none"
              stroke={c.artGrey}
              strokeWidth={3.15}
            />
            <Path
              d="M-21.36 -45.92C-53.4 -55.76 -106.8 -55.76 -153.08 -49.2"
              fill="none"
              stroke={c.artGrey}
              strokeWidth={3.15}
            />
            <Path
              d="M-21.36 -32.8C-53.4 -42.64 -106.8 -42.64 -153.08 -36.08"
              fill="none"
              stroke={c.artGrey}
              strokeWidth={3.15}
            />
            <Path
              d="M-21.36 -19.68C-53.4 -29.52 -106.8 -29.52 -153.08 -22.96"
              fill="none"
              stroke={c.artGrey}
              strokeWidth={3.15}
            />
            <Path
              d="M0 0C44.5 -16.4 106.8 -16.4 178 -5.74V-77.08C106.8 -88.56 44.5 -88.56 0 -70.52Z"
              fill={c.artPaper}
            />
            <Path
              d="M0 0C44.5 -16.4 106.8 -16.4 178 -5.74V-77.08C106.8 -88.56 44.5 -88.56 0 -70.52Z"
              fill={c.artShade}
            />
            <Path
              d="M0 0C44.5 -16.4 106.8 -16.4 178 -5.74V-77.08C106.8 -88.56 44.5 -88.56 0 -70.52Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={3.5}
            />
            <Path
              d="M21.36 -59.04C53.4 -68.88 106.8 -68.88 153.08 -62.32"
              fill="none"
              stroke={c.artGrey}
              strokeWidth={3.15}
            />
            <Path
              d="M21.36 -45.92C53.4 -55.76 106.8 -55.76 153.08 -49.2"
              fill="none"
              stroke={c.artGrey}
              strokeWidth={3.15}
            />
            <Path
              d="M21.36 -32.8C53.4 -42.64 106.8 -42.64 153.08 -36.08"
              fill="none"
              stroke={c.artGrey}
              strokeWidth={3.15}
            />
            <Path
              d="M21.36 -19.68C53.4 -29.52 106.8 -29.52 153.08 -22.96"
              fill="none"
              stroke={c.artGrey}
              strokeWidth={3.15}
            />
            <Line x1={0} y1={-70.52} x2={0} y2={0} stroke={c.artInk} strokeWidth={3.5} />
          </G>
          <Path
            d="M92 81Q95.08 88.92 103 92Q95.08 95.08 92 103Q88.92 95.08 81 92Q88.92 88.92 92 81Z"
            fill={c.gold}
          />
          <Path
            d="M520 112Q522.24 117.76 528 120Q522.24 122.24 520 128Q517.76 122.24 512 120Q517.76 117.76 520 112Z"
            fill={c.gold}
          />
          <Circle cx={250} cy={70} r={5} fill={c.accent} />
        </G>
      </Svg>
    </View>
  );
}
