// Generated by scripts/render-art.mjs from its drawing of B19; change the drawing there and rerun.
import { View } from 'react-native';
import Svg, { Circle, Ellipse, G, Line, Path, Rect } from 'react-native-svg';

import { usePalette } from '@/theme';

/**
 * B19: A gold dollar coin standing beside a stack of three books.
 * Artboard 360 x 160; `width` scales it. Decorative (hidden from screen readers) unless
 * a `label` is given. Colours come from the palette, so one drawing serves light and dark.
 */
export function PlansHeader({ width = 360, label }: { width?: number; label?: string }) {
  const c = usePalette();
  return (
    <View
      role={label ? 'img' : undefined}
      aria-label={label}
      aria-hidden={!label}
      importantForAccessibility={label ? 'yes' : 'no-hide-descendants'}
    >
      <Svg width={width} height={width * 0.4444444444444444} viewBox={'0 0 360 160'}>
        <G strokeLinecap="round" strokeLinejoin="round">
          <Ellipse cx={180} cy={84} rx={150} ry={70} fill={c.accentSoft} />
          <Ellipse cx={186} cy={141} rx={110} ry={4} fill={c.artShade} />
          <G transform="translate(98 140) scale(1)">
            <Path
              d="M5.28 -24H126.72Q132 -24 132 -18.72V-5.28Q132 0 126.72 0H5.28Q0 0 0 -5.28V-18.72Q0 -24 5.28 -24Z"
              fill={c.accent}
            />
            <Path
              d="M5.28 -24H126.72Q132 -24 132 -18.72V-5.28Q132 0 126.72 0H5.28Q0 0 0 -5.28V-18.72Q0 -24 5.28 -24Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.5}
            />
            <Path
              d="M13.44 -19.68H123.84Q126.72 -19.68 126.72 -16.8V-7.2Q126.72 -4.32 123.84 -4.32H13.44Q10.56 -4.32 10.56 -7.2V-16.8Q10.56 -19.68 13.44 -19.68Z"
              fill={c.artPaper}
              stroke={c.artInk}
              strokeWidth={2}
            />
            <Line
              x1={15.84}
              y1={-15.84}
              x2={124.08}
              y2={-15.84}
              stroke={c.artGrey}
              strokeWidth={1.5}
            />
            <Line x1={15.84} y1={-12} x2={124.08} y2={-12} stroke={c.artGrey} strokeWidth={1.5} />
            <Line
              x1={15.84}
              y1={-8.16}
              x2={124.08}
              y2={-8.16}
              stroke={c.artGrey}
              strokeWidth={1.5}
            />
            <Rect x={10.56} y={-24} width={7.92} height={24} fill={c.artShade} />
          </G>
          <G transform="translate(110 116) scale(1)">
            <Path
              d="M4.84 -22H111.16Q116 -22 116 -17.16V-4.84Q116 0 111.16 0H4.84Q0 0 0 -4.84V-17.16Q0 -22 4.84 -22Z"
              fill={c.artRose}
            />
            <Path
              d="M4.84 -22H111.16Q116 -22 116 -17.16V-4.84Q116 0 111.16 0H4.84Q0 0 0 -4.84V-17.16Q0 -22 4.84 -22Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.5}
            />
            <Path
              d="M11.92 -18.04H108.72Q111.36 -18.04 111.36 -15.4V-6.6Q111.36 -3.96 108.72 -3.96H11.92Q9.28 -3.96 9.28 -6.6V-15.4Q9.28 -18.04 11.92 -18.04Z"
              fill={c.artPaper}
              stroke={c.artInk}
              strokeWidth={2}
            />
            <Line
              x1={13.92}
              y1={-14.52}
              x2={109.04}
              y2={-14.52}
              stroke={c.artGrey}
              strokeWidth={1.5}
            />
            <Line x1={13.92} y1={-11} x2={109.04} y2={-11} stroke={c.artGrey} strokeWidth={1.5} />
            <Line
              x1={13.92}
              y1={-7.48}
              x2={109.04}
              y2={-7.48}
              stroke={c.artGrey}
              strokeWidth={1.5}
            />
            <Rect x={9.28} y={-22} width={6.96} height={22} fill={c.artShade} />
          </G>
          <G transform="translate(102 94) scale(1)">
            <Path
              d="M4.4 -20H119.6Q124 -20 124 -15.6V-4.4Q124 0 119.6 0H4.4Q0 0 0 -4.4V-15.6Q0 -20 4.4 -20Z"
              fill={c.artPaper}
            />
            <Path
              d="M4.4 -20H119.6Q124 -20 124 -15.6V-4.4Q124 0 119.6 0H4.4Q0 0 0 -4.4V-15.6Q0 -20 4.4 -20Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.5}
            />
            <Path
              d="M12.32 -16.4H116.64Q119.04 -16.4 119.04 -14V-6Q119.04 -3.6 116.64 -3.6H12.32Q9.92 -3.6 9.92 -6V-14Q9.92 -16.4 12.32 -16.4Z"
              fill={c.artPaper}
              stroke={c.artInk}
              strokeWidth={2}
            />
            <Line
              x1={14.88}
              y1={-13.2}
              x2={116.56}
              y2={-13.2}
              stroke={c.artGrey}
              strokeWidth={1.5}
            />
            <Line x1={14.88} y1={-10} x2={116.56} y2={-10} stroke={c.artGrey} strokeWidth={1.5} />
            <Line x1={14.88} y1={-6.8} x2={116.56} y2={-6.8} stroke={c.artGrey} strokeWidth={1.5} />
            <Rect x={9.92} y={-20} width={7.44} height={20} fill={c.artShade} />
          </G>
          <G transform="translate(276 96) scale(1)">
            <Circle cx={5.16} cy={0} r={43} fill={c.goldDeep} stroke={c.artInk} strokeWidth={2.5} />
            <Circle cx={0} cy={0} r={43} fill={c.gold} stroke={c.artInk} strokeWidth={2.5} />
            <Circle cx={0} cy={0} r={34.4} fill="none" stroke={c.goldDeep} strokeWidth={2.25} />
            <Line x1={36.98} y1={0} x2={40.42} y2={0} stroke={c.goldDeep} strokeWidth={1.25} />
            <Line
              x1={35.72}
              y1={9.57}
              x2={39.04}
              y2={10.46}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line x1={32.03} y1={18.49} x2={35} y2={20.21} stroke={c.goldDeep} strokeWidth={1.25} />
            <Line
              x1={26.15}
              y1={26.15}
              x2={28.58}
              y2={28.58}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line x1={18.49} y1={32.03} x2={20.21} y2={35} stroke={c.goldDeep} strokeWidth={1.25} />
            <Line
              x1={9.57}
              y1={35.72}
              x2={10.46}
              y2={39.04}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line x1={0} y1={36.98} x2={0} y2={40.42} stroke={c.goldDeep} strokeWidth={1.25} />
            <Line
              x1={-9.57}
              y1={35.72}
              x2={-10.46}
              y2={39.04}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={-18.49}
              y1={32.03}
              x2={-20.21}
              y2={35}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={-26.15}
              y1={26.15}
              x2={-28.58}
              y2={28.58}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={-32.03}
              y1={18.49}
              x2={-35}
              y2={20.21}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={-35.72}
              y1={9.57}
              x2={-39.04}
              y2={10.46}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line x1={-36.98} y1={0} x2={-40.42} y2={0} stroke={c.goldDeep} strokeWidth={1.25} />
            <Line
              x1={-35.72}
              y1={-9.57}
              x2={-39.04}
              y2={-10.46}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={-32.03}
              y1={-18.49}
              x2={-35}
              y2={-20.21}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={-26.15}
              y1={-26.15}
              x2={-28.58}
              y2={-28.58}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={-18.49}
              y1={-32.03}
              x2={-20.21}
              y2={-35}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={-9.57}
              y1={-35.72}
              x2={-10.46}
              y2={-39.04}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line x1={0} y1={-36.98} x2={0} y2={-40.42} stroke={c.goldDeep} strokeWidth={1.25} />
            <Line
              x1={9.57}
              y1={-35.72}
              x2={10.46}
              y2={-39.04}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={18.49}
              y1={-32.03}
              x2={20.21}
              y2={-35}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={26.15}
              y1={-26.15}
              x2={28.58}
              y2={-28.58}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={32.03}
              y1={-18.49}
              x2={35}
              y2={-20.21}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={35.72}
              y1={-9.57}
              x2={39.04}
              y2={-10.46}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Path
              d="M10.21 -11.14C6.5 -16.71 -11.14 -16.71 -10.21 -6.5C-9.28 1.86 10.21 -1.86 10.21 7.43C10.21 17.64 -7.43 17.64 -11.14 10.21"
              fill="none"
              stroke={c.goldDeep}
              strokeWidth={5.59}
            />
            <Line x1={0} y1={-20.42} x2={0} y2={20.43} stroke={c.goldDeep} strokeWidth={5.59} />
            <Path
              d="M-26.66 -16.34A30.96 30.96 0 0 1 -8.6 -30.1"
              fill="none"
              stroke={c.artShine}
              strokeWidth={3.87}
            />
          </G>
          <Path
            d="M318 32Q320.24 37.76 326 40Q320.24 42.24 318 48Q315.76 42.24 310 40Q315.76 37.76 318 32Z"
            fill={c.gold}
          />
          <Path
            d="M70 44Q71.68 48.32 76 50Q71.68 51.68 70 56Q68.32 51.68 64 50Q68.32 48.32 70 44Z"
            fill={c.gold}
          />
          <Circle cx={232} cy={34} r={3.5} fill={c.accent} />
        </G>
      </Svg>
    </View>
  );
}
