// Generated by scripts/render-art.mjs from its drawing of B20; change the drawing there and rerun.
import { View } from 'react-native';
import Svg, { Circle, G, Line, Path } from 'react-native-svg';

import { usePalette } from '@/theme';

/** The check stroke on its own (artboard coordinates), for the draw animation. */
export const PURCHASE_CHECK = { d: 'M105.5 114.5L112.5 121.5L127 106.5', width: 5, length: 30.76 };

/**
 * B20: The dollar coin from B19 with a check-mark badge; the check is a separate path for the draw animation.
 * Artboard 160 x 160; `width` scales it. Decorative (hidden from screen readers) unless
 * a `label` is given. Colours come from the palette, so one drawing serves light and dark.
 * `checkProgress` (0 to 1) draws the check stroke; animate it, or animate
 * `PURCHASE_CHECK` with your own path, for the 400 ms check draw.
 */
export function PurchaseSuccess({
  width = 160,
  label,
  checkProgress = 1,
}: {
  width?: number;
  label?: string;
  checkProgress?: number;
}) {
  const c = usePalette();
  return (
    <View
      role={label ? 'img' : undefined}
      aria-label={label}
      aria-hidden={!label}
      importantForAccessibility={label ? 'yes' : 'no-hide-descendants'}
    >
      <Svg width={width} height={width * 1} viewBox={'0 0 160 160'}>
        <G strokeLinecap="round" strokeLinejoin="round">
          <Circle cx={80} cy={80} r={72} fill={c.accentSoft} />
          <G transform="translate(72 74) scale(1)">
            <Circle cx={5.76} cy={0} r={48} fill={c.goldDeep} stroke={c.artInk} strokeWidth={2.5} />
            <Circle cx={0} cy={0} r={48} fill={c.gold} stroke={c.artInk} strokeWidth={2.5} />
            <Circle cx={0} cy={0} r={38.4} fill="none" stroke={c.goldDeep} strokeWidth={2.25} />
            <Line x1={41.28} y1={0} x2={45.12} y2={0} stroke={c.goldDeep} strokeWidth={1.25} />
            <Line
              x1={39.87}
              y1={10.68}
              x2={43.58}
              y2={11.68}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={35.75}
              y1={20.64}
              x2={39.08}
              y2={22.56}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={29.19}
              y1={29.19}
              x2={31.9}
              y2={31.9}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={20.64}
              y1={35.75}
              x2={22.56}
              y2={39.08}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={10.68}
              y1={39.87}
              x2={11.68}
              y2={43.58}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line x1={0} y1={41.28} x2={0} y2={45.12} stroke={c.goldDeep} strokeWidth={1.25} />
            <Line
              x1={-10.68}
              y1={39.87}
              x2={-11.68}
              y2={43.58}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={-20.64}
              y1={35.75}
              x2={-22.56}
              y2={39.08}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={-29.19}
              y1={29.19}
              x2={-31.9}
              y2={31.9}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={-35.75}
              y1={20.64}
              x2={-39.08}
              y2={22.56}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={-39.87}
              y1={10.68}
              x2={-43.58}
              y2={11.68}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line x1={-41.28} y1={0} x2={-45.12} y2={0} stroke={c.goldDeep} strokeWidth={1.25} />
            <Line
              x1={-39.87}
              y1={-10.68}
              x2={-43.58}
              y2={-11.68}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={-35.75}
              y1={-20.64}
              x2={-39.08}
              y2={-22.56}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={-29.19}
              y1={-29.19}
              x2={-31.9}
              y2={-31.9}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={-20.64}
              y1={-35.75}
              x2={-22.56}
              y2={-39.08}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={-10.68}
              y1={-39.87}
              x2={-11.68}
              y2={-43.58}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line x1={0} y1={-41.28} x2={0} y2={-45.12} stroke={c.goldDeep} strokeWidth={1.25} />
            <Line
              x1={10.68}
              y1={-39.87}
              x2={11.68}
              y2={-43.58}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={20.64}
              y1={-35.75}
              x2={22.56}
              y2={-39.08}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={29.19}
              y1={-29.19}
              x2={31.9}
              y2={-31.9}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={35.75}
              y1={-20.64}
              x2={39.08}
              y2={-22.56}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Line
              x1={39.87}
              y1={-10.68}
              x2={43.58}
              y2={-11.68}
              stroke={c.goldDeep}
              strokeWidth={1.25}
            />
            <Path
              d="M11.4 -12.44C7.25 -18.65 -12.44 -18.65 -11.4 -7.25C-10.36 2.07 11.4 -2.07 11.4 8.29C11.4 19.69 -8.29 19.69 -12.44 11.4"
              fill="none"
              stroke={c.goldDeep}
              strokeWidth={6.24}
            />
            <Line x1={0} y1={-22.8} x2={0} y2={22.8} stroke={c.goldDeep} strokeWidth={6.24} />
            <Path
              d="M-29.76 -18.24A34.56 34.56 0 0 1 -9.6 -33.6"
              fill="none"
              stroke={c.artShine}
              strokeWidth={4.32}
            />
          </G>
          <Circle cx={116} cy={114} r={25} fill={c.success} stroke={c.card} strokeWidth={5} />
          <Circle cx={116} cy={114} r={22.5} fill="none" stroke={c.artInk} strokeWidth={2.5} />
          <Path
            d={PURCHASE_CHECK.d}
            fill="none"
            stroke={c.onAccent}
            strokeWidth={PURCHASE_CHECK.width}
            strokeDasharray={PURCHASE_CHECK.length}
            strokeDashoffset={PURCHASE_CHECK.length * (1 - checkProgress)}
          />
        </G>
      </Svg>
    </View>
  );
}
