// Generated by scripts/render-art.mjs from its drawing of B18; change the drawing there and rerun.
import { View } from 'react-native';
import Svg, { Circle, G, Path, Rect } from 'react-native-svg';

import { usePalette } from '@/theme';

/**
 * B18: A magnifier over a worksheet with one line highlighted.
 * Artboard 240 x 160; `width` scales it. Decorative (hidden from screen readers) unless
 * a `label` is given. Colours come from the palette, so one drawing serves light and dark.
 */
export function SearchStart({ width = 240, label }: { width?: number; label?: string }) {
  const c = usePalette();
  return (
    <View
      role={label ? 'img' : undefined}
      aria-label={label}
      aria-hidden={!label}
      importantForAccessibility={label ? 'yes' : 'no-hide-descendants'}
    >
      <Svg width={width} height={width * 0.6666666666666666} viewBox={'0 0 240 160'}>
        <G strokeLinecap="round" strokeLinejoin="round">
          <Circle cx={120} cy={80} r={70} fill={c.accentSoft} />
          <Path
            d="M74 26H158Q166 26 166 34V134Q166 142 158 142H74Q66 142 66 134V34Q66 26 74 26Z"
            fill={c.artShade}
          />
          <Path
            d="M68 20H152Q160 20 160 28V128Q160 136 152 136H68Q60 136 60 128V28Q60 20 68 20Z"
            fill={c.artPaper}
            stroke={c.artInk}
            strokeWidth={2.25}
          />
          <Rect x={74} y={34} width={46} height={6} fill={c.accent} rx={3} />
          <Rect x={74} y={50} width={72} height={6} fill={c.artGrey} rx={3} />
          <Rect x={74} y={64} width={62} height={6} fill={c.artGrey} rx={3} />
          <Rect x={68} y={75} width={86} height={14} fill={c.gold} rx={4} fillOpacity={0.55} />
          <Rect x={74} y={79} width={70} height={6} fill={c.artInk} rx={3} />
          <Rect x={74} y={96} width={66} height={6} fill={c.artGrey} rx={3} />
          <Rect x={74} y={110} width={72} height={6} fill={c.artGrey} rx={3} />
          <Rect x={74} y={124} width={40} height={6} fill={c.artGrey} rx={3} />
          <G transform="translate(150 82) scale(1)">
            <Path d="M16.3 23.65L23.65 16.3L41.37 34.01L34.01 41.37Z" fill={c.accent} />
            <Path
              d="M16.3 23.65L23.65 16.3L41.37 34.01L34.01 41.37Z"
              fill="none"
              stroke={c.artInk}
              strokeWidth={2.25}
            />
            <Circle cx={0} cy={0} r={26} fill={c.artPaper} fillOpacity={0.55} />
            <Rect x={-24} y={-9} width={48} height={18} fill={c.gold} fillOpacity={0.55} />
            <Rect x={-24} y={-5} width={40} height={10} fill={c.artInk} rx={5} />
            <Path
              d="M-16.12 -3.12A16.64 16.64 0 0 1 -3.12 -16.12"
              fill="none"
              stroke={c.artShine}
              strokeWidth={4.16}
            />
            <Circle cx={0} cy={0} r={26} fill="none" stroke={c.artGrey} strokeWidth={5.2} />
            <Circle cx={0} cy={0} r={28.6} fill="none" stroke={c.artInk} strokeWidth={2.25} />
            <Circle cx={0} cy={0} r={23.4} fill="none" stroke={c.artInk} strokeWidth={1.8} />
          </G>
        </G>
      </Svg>
    </View>
  );
}
