// Generated by scripts/render-art.mjs from its drawing of B24; change the drawing there and rerun.
import { View } from 'react-native';
import Svg, { Circle, G, Line, Path, Rect } from 'react-native-svg';

import { usePalette } from '@/theme';

/**
 * B24: A plug pulled out of its socket (error, offline).
 * Artboard 240 x 160; `width` scales it. Decorative (hidden from screen readers) unless
 * a `label` is given. Colours come from the palette, so one drawing serves light and dark.
 */
export function Unplugged({ width = 240, label }: { width?: number; label?: string }) {
  const c = usePalette();
  return (
    <View
      role={label ? 'img' : undefined}
      aria-label={label}
      aria-hidden={!label}
      importantForAccessibility={label ? 'yes' : 'no-hide-descendants'}
    >
      <Svg width={width} height={width * 0.6666666666666666} viewBox={'0 0 240 160'}>
        <G strokeLinecap="round" strokeLinejoin="round">
          <Circle cx={120} cy={80} r={70} fill={c.accentSoft} />
          <Path
            d="M170 44H202Q212 44 212 54V104Q212 114 202 114H170Q160 114 160 104V54Q160 44 170 44Z"
            fill={c.artPaper}
            stroke={c.artInk}
            strokeWidth={2.25}
          />
          <Path
            d="M175 51H197Q205 51 205 59V99Q205 107 197 107H175Q167 107 167 99V59Q167 51 175 51Z"
            fill={c.artGrey}
            stroke={c.artInk}
            strokeWidth={1.5}
          />
          <Rect x={176} y={66} width={5} height={14} fill={c.artInk} rx={2} />
          <Rect x={191} y={66} width={5} height={14} fill={c.artInk} rx={2} />
          <Circle cx={186} cy={94} r={3} fill={c.artInk} />
          <Path d="M20 140C60 140 50 84 92 84" fill="none" stroke={c.artInk} strokeWidth={6.5} />
          <Path d="M20 140C60 140 50 84 92 84" fill="none" stroke={c.accent} strokeWidth={3} />
          <Rect
            x={132}
            y={75}
            width={16}
            height={5}
            fill={c.gold}
            stroke={c.artInk}
            strokeWidth={1.5}
          />
          <Rect
            x={132}
            y={88}
            width={16}
            height={5}
            fill={c.gold}
            stroke={c.artInk}
            strokeWidth={1.5}
          />
          <Path
            d="M97 70H127Q134 70 134 77V91Q134 98 127 98H97Q90 98 90 91V77Q90 70 97 70Z"
            fill={c.accent}
          />
          <Path
            d="M97 70H127Q134 70 134 77V91Q134 98 127 98H97Q90 98 90 91V77Q90 70 97 70Z"
            fill="none"
            stroke={c.artInk}
            strokeWidth={2.25}
          />
          <Rect x={96} y={74} width={30} height={4} fill={c.artShine} rx={2} />
          <Line x1={152} y1={60} x2={146} y2={52} stroke={c.artInk} strokeWidth={2.25} />
          <Line x1={154} y1={84} x2={148} y2={84} stroke={c.artInk} strokeWidth={2.25} />
          <Line x1={152} y1={108} x2={146} y2={116} stroke={c.artInk} strokeWidth={2.25} />
          <Path
            d="M56 35Q57.96 40.04 63 42Q57.96 43.96 56 49Q54.04 43.96 49 42Q54.04 40.04 56 35Z"
            fill={c.gold}
          />
        </G>
      </Svg>
    </View>
  );
}
