#!/usr/bin/env python3
"""Check the college tables of contents and write the college crosswalks.

Usage:
  python3 research/textbooks/tools/build_college.py                    # check only (exit 1 on error)
  python3 research/textbooks/tools/build_college.py --fields math,physics  # also write college/<field>.md
  python3 research/textbooks/tools/build_college.py --index            # also write college/CROSSWALK.md
  python3 research/textbooks/tools/build_college.py --all              # every field page and the index

Reads research/textbooks/toc/college/<book-id>.json (format: docs/RESEARCH_HE.md, "Recording
format") and research/questions/college/<field>.jsonl (checked by
research/questions/validate_college.py). Checks, for every table of contents:

- the keys id (= file name), curriculum, publisher, edition, subject (a field id of HE_FIELDS),
  level ("college"), content ("titles" or "full"), license {name, url, attribution}, terms,
  sourceUrl, retrieved (YYYY-MM-DD), notes and books;
- every unit has `topics` (a section without `topics` inherits its unit's); every topic id is a
  real `<courseId>#<i>` of COURSES; an empty `topics` list carries a `note` (a taxonomy gap; a section may
  share the note of a unit that has no topic either);
- a "titles" file holds titles only: no `examples`, `ranges` or `notation` anywhere;
- `examples`, `ranges` and `notation` are lists of strings where present.

A field page `college/<field>.md` covers the courses whose home field (first field) is that
field: per topic, the units and sections of each book that teach it (book order), their example
kinds, ranges and notation, and the question records; each book's order through the course's
topics; and the sections no topic fits. Text above the line `<!-- generated by
build_college.py -->` in an existing field page is kept; everything below it is rewritten.
"""
import collections, glob, importlib.util, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.dirname(HERE)  # research/textbooks
ROOT = os.path.dirname(os.path.dirname(BASE))
TOC = os.path.join(BASE, "toc", "college")
OUT = os.path.join(BASE, "college")
MARKER = "<!-- generated by build_college.py -->"
KEYS = ["id", "curriculum", "publisher", "edition", "subject", "level", "content", "license",
        "terms", "sourceUrl", "retrieved", "notes", "books"]
DETAIL = ("examples", "ranges", "notation")

spec = importlib.util.spec_from_file_location(
    "vcollege", os.path.join(ROOT, "research", "questions", "validate_college.py"))
vcollege = importlib.util.module_from_spec(spec)
spec.loader.exec_module(vcollege)


def load_tocs(errors):
    tocs = []
    for path in sorted(glob.glob(os.path.join(TOC, "*.json"))):
        rel = os.path.relpath(path, BASE)
        try:
            t = json.load(open(path, encoding="utf-8"))
        except ValueError as e:
            errors.append(f"{rel}: {e}")
            continue
        t["_path"] = rel
        tocs.append(t)
    return tocs


def walk(node, inherited, trail):
    """Yield (node, effective topics, trail of (n, title)) for every unit and section, in order."""
    topics = node.get("topics", inherited)
    trail = trail + [(node.get("n"), node.get("title"))]
    yield node, topics, trail
    for s in node.get("sections") or []:
        yield from walk(s, topics, trail)


def nodes_of(toc):
    for bi, b in enumerate(toc.get("books", [])):
        for u in b.get("units", []):
            for node, topics, trail in walk(u, None, []):
                yield bi, b, node, topics, trail


def label(trail):
    """"3.2 Title" from the deepest numbered level, else the title alone."""
    nums = [str(n) for n, _ in trail if n not in (None, "")]
    title = trail[-1][1] or ""
    num = trail[-1][0]
    if num in (None, ""):
        return title
    # Section numbers that already carry their unit ("3.2") are shown as they are.
    return f"{num} {title}" if "." in str(num) or len(nums) == 1 else f"{'.'.join(nums)} {title}"


def check(tocs, fields, topics, errors):
    seen = set()
    for t in tocs:
        p = t["_path"]
        for k in KEYS:
            if k not in t:
                errors.append(f"{p}: missing {k}")
        stem = os.path.splitext(os.path.basename(p))[0]
        if t.get("id") != stem:
            errors.append(f"{p}: id {t.get('id')!r} does not match the file name")
        if t.get("id") in seen:
            errors.append(f"{p}: duplicate id {t.get('id')}")
        seen.add(t.get("id"))
        if t.get("subject") not in fields:
            errors.append(f"{p}: subject {t.get('subject')!r} is not a field id of HE_FIELDS")
        if t.get("level") != "college":
            errors.append(f"{p}: level must be \"college\"")
        if t.get("content") not in ("titles", "full"):
            errors.append(f"{p}: content must be \"titles\" or \"full\"")
        lic = t.get("license")
        if not (isinstance(lic, dict) and {"name", "url", "attribution"} <= set(lic)):
            errors.append(f"{p}: license needs name/url/attribution")
        if not (isinstance(t.get("retrieved"), str) and vcollege.DATE.match(t["retrieved"])):
            errors.append(f"{p}: retrieved must be YYYY-MM-DD")
        if not isinstance(t.get("books"), list) or not t.get("books"):
            errors.append(f"{p}: books must be a non-empty list")
            continue
        for bi, b in enumerate(t["books"]):
            if not b.get("title"):
                errors.append(f"{p}: book {bi} has no title")
            if not b.get("units"):
                errors.append(f"{p}: book {bi} has no units")
            for u in b.get("units", []):
                if "topics" not in u:
                    errors.append(f"{p}: book {bi} unit {u.get('n')} {u.get('title')!r}: no topics")
        # Sections with no topic inside a unit with no topic share the unit's note.
        covered = {id(s) for b in t["books"] for u in b.get("units", [])
                   if u.get("topics") == [] and u.get("note") for s, _, _ in walk(u, None, [])}
        for bi, b, node, tps, trail in nodes_of(t):
            where = f"{p}: {label(trail)!r}"
            if not node.get("title"):
                errors.append(f"{where}: no title")
            if tps is None:
                continue
            if not isinstance(tps, list):
                errors.append(f"{where}: topics must be a list")
                continue
            for tid in tps:
                if tid not in topics:
                    errors.append(f"{where}: unknown topic {tid}")
            if "topics" in node and not node["topics"] and not node.get("note") and id(node) not in covered:
                errors.append(f"{where}: empty topics needs a note (the taxonomy gap)")
            for k in DETAIL:
                if k in node:
                    if t.get("content") == "titles":
                        errors.append(f"{where}: {k} in a titles-only file")
                    elif not (isinstance(node[k], list) and all(isinstance(x, str) for x in node[k])):
                        errors.append(f"{where}: {k} must be a list of strings")


def md(s):
    return str(s).replace("|", "\\|").replace("\n", " ")


def course_field(cid, courses):
    return courses[cid]["fields"][0]


def teaching(tocs, topics):
    """{topic id: [(toc, book, node, trail, own)]} in toc order; own = the node names it itself."""
    out = collections.defaultdict(list)
    for t in tocs:
        for bi, b, node, tps, trail in nodes_of(t):
            for tid in tps or []:
                if tid in topics:
                    out[tid].append((t, b, node, trail, "topics" in node))
    return out


def book_name(t, b):
    return t["id"] if len(t["books"]) == 1 else f"{t['id']} ({b.get('title')})"


def field_page(field, ftitle, tocs, courses, topics, recs):
    teach = teaching(tocs, topics)
    mine = [c for c in courses if course_field(c, courses) == field]
    out = [MARKER, "",
           f"Generated by `research/textbooks/tools/build_college.py` from `toc/college/*.json` and",
           "`../../questions/college/*.jsonl`; edit those, not the text below. Reference only",
           "(`research/README.md`): nothing here goes into a lesson, picture or test.", ""]
    used = sorted({t["id"] for tid in topics if tid.split("#")[0] in mine for t, *_ in teach.get(tid, [])})
    out.append(f"## Books ({len(used)})\n")
    out.append("| Book | Title | Publisher | Content | Licence |\n| --- | --- | --- | --- | --- |")
    for t in tocs:
        if t["id"] in used:
            out.append(f"| `{t['id']}` | [{md(t['curriculum'])}]({t['sourceUrl']}) | {md(t['publisher'])} | "
                       f"{t['content']} | {md(t['license']['name'])} |")
    out.append("")
    for cid in mine:
        c = courses[cid]
        n = sum(1 for r in recs if r.get("courseId") == cid)
        out.append(f"## {md(c['title'])} (`{cid}`)\n")
        out.append(f"Question records: {n}" + (f" (target {vcollege.target_of(cid, courses)})"
                                                 if vcollege.target_of(cid, courses) else "") + ".\n")
        for i, title in enumerate(c["topics"]):
            tid = f"{cid}#{i}"
            q = [r for r in recs if r.get("topicId") == tid]
            qa = [r for r in recs if tid in (r.get("alsoTopics") or [])]
            out.append(f"### `{tid}` {md(title)}\n")
            out.append(f"Records: {len(q)} filed, {len(qa)} also.\n")
            # Sections that name the topic, and inherited ones that record examples or notation.
            rows = [x for x in teach.get(tid, []) if x[4] or any(k in x[2] for k in DETAIL)]
            if not rows:
                out.append("No book section maps to this topic yet.\n")
                continue
            out.append("| Book | Where | Examples | Ranges | Notation |\n| --- | --- | --- | --- | --- |")
            for t, b, node, trail, _ in rows:
                where = " › ".join(md(label(trail[:k + 1])) for k in range(len(trail)))
                out.append(f"| `{md(book_name(t, b))}` | {where} | "
                           f"{'; '.join(md(x) for x in node.get('examples', []))} | "
                           f"{'; '.join(md(x) for x in node.get('ranges', []))} | "
                           f"{'; '.join(md(x) for x in node.get('notation', []))} |")
            out.append("")
        # Each book's order through this course's topics (first appearance).
        order = []
        for t in tocs:
            for bi, b in enumerate(t["books"]):
                seq = []
                for u in b.get("units", []):
                    for node, tps, trail in walk(u, None, []):
                        for tid in tps or []:
                            if tid.startswith(cid + "#"):
                                k = int(tid.split("#")[1])
                                if k not in seq:
                                    seq.append(k)
                if seq:
                    missing = [k for k in range(len(c["topics"])) if k not in seq]
                    order.append(f"| `{md(book_name(t, b))}` | {' → '.join('#' + str(k) for k in seq)} | "
                                 f"{', '.join('#' + str(k) for k in missing) or '—'} |")
        if order:
            out.append("**Order the books teach the topics in**\n")
            out.append("| Book | Order | Not taught |\n| --- | --- | --- |")
            out += order
            out.append("")
    gaps = []
    for t in tocs:
        if t.get("subject") != field:
            continue
        for bi, b, node, tps, trail in nodes_of(t):
            if "topics" in node and node["topics"] == []:
                gaps.append(f"- `{md(book_name(t, b))}` {md(label(trail))}: {md(node.get('note', ''))}")
    out.append(f"## Taught by the books, not in the taxonomy ({len(gaps)})\n")
    out += gaps or ["None recorded."]
    return "\n".join(out) + "\n"


def write_field(field, ftitle, text):
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, f"{field}.md")
    head = (f"# {ftitle}: what college textbooks teach\n\n"
            "Crosswalk from the college topics of `src/data/taxonomy.ts` to the books in\n"
            "`toc/college/`. Notes above the marker line are kept when the page is rebuilt.\n\n")
    if os.path.exists(path):
        old = open(path, encoding="utf-8").read()
        if MARKER in old:
            head = old[:old.index(MARKER)]
    with open(path, "w", encoding="utf-8") as f:
        f.write(head + text)
    return path


def index(tocs, fields, courses, topics, recs):
    teach = teaching(tocs, topics)
    out = ["# College crosswalk: topics → books and questions\n",
           "Generated by `tools/build_college.py`; don't edit by hand. For each college topic of",
           "`src/data/taxonomy.ts` (`COURSES`): the books in `toc/college/` whose units or sections",
           "teach it, and the question records in `../../questions/college/`. The field pages",
           "(`<field>.md`) give the sections, example kinds, ranges and notation.\n",
           "## Books\n",
           "| Book | Title | Field | Content | Licence | Retrieved |\n| --- | --- | --- | --- | --- | --- |"]
    for t in tocs:
        out.append(f"| `{t['id']}` | [{md(t['curriculum'])}]({t['sourceUrl']}) | {t['subject']} | "
                   f"{t['content']} | {md(t['license']['name'])} | {t['retrieved']} |")
    out.append("")
    for f, ftitle in fields.items():
        mine = [c for c in courses if course_field(c, courses) == f]
        if not mine:
            continue
        page = f"[{f}.md]({f}.md)" if os.path.exists(os.path.join(OUT, f"{f}.md")) else "no field page yet"
        out.append(f"## {ftitle} ({page})\n")
        out.append("| Topic | Title | Books | Records |\n| --- | --- | --- | ---: |")
        for cid in mine:
            for i, title in enumerate(courses[cid]["topics"]):
                tid = f"{cid}#{i}"
                books = sorted({t["id"] for t, b, node, trail, own in teach.get(tid, []) if own})
                n = sum(1 for r in recs if r.get("topicId") == tid)
                out.append(f"| `{tid}` | {md(title)} | {', '.join(f'`{b}`' for b in books) or '—'} | {n or ''} |")
        out.append("")
    none = [tid for tid in topics if not any(own for *_, own in teach.get(tid, []))]
    out.append(f"**Topics no book maps to ({len(none)}):** " + (", ".join(f"`{x}`" for x in none) or "none") + "\n")
    return "\n".join(out)


def main():
    errors = []
    fields, courses = vcollege.load_taxonomy()
    topics = vcollege.topic_ids(courses)
    tocs = load_tocs(errors)
    check(tocs, fields, topics, errors)
    recs, qerr = vcollege.load_records()
    qerr = vcollege.validate(recs, fields, courses, qerr, [])
    errors += [f"questions: {e}" for e in qerr]
    for e in errors:
        print("ERROR", e)
    print(f"{len(tocs)} college tables of contents ({sum(t.get('content') == 'full' for t in tocs)} full), "
          f"{len(recs)} question records")
    if errors:
        sys.exit(1)
    want = set()
    if "--all" in sys.argv:
        want = {course_field(c, courses) for c in courses}
    elif "--fields" in sys.argv:
        want = set(sys.argv[sys.argv.index("--fields") + 1].split(","))
    for f in sorted(want):
        if f not in fields:
            raise SystemExit(f"unknown field {f}")
        print("wrote", os.path.relpath(write_field(f, fields[f], field_page(f, fields[f], tocs, courses, topics, recs)), ROOT))
    if "--all" in sys.argv or "--index" in sys.argv:
        os.makedirs(OUT, exist_ok=True)
        with open(os.path.join(OUT, "CROSSWALK.md"), "w", encoding="utf-8") as fh:
            fh.write(index(tocs, fields, courses, topics, recs))
        print("wrote research/textbooks/college/CROSSWALK.md")


if __name__ == "__main__":
    main()
