// Copies the Tabler icons (MIT license, https://tabler.io/icons) that the Browse boxes use into
// src/icons/tabler.ts, so the app needs no icon package.
//
//   npm pack @tabler/icons && tar xzf tabler-icons-*.tgz   (anywhere outside the project)
//   node scripts/vendor-icons.mjs <path to package/icons/outline>
//
// Icons used are the quoted names in src/data/icons.ts that are Tabler file names and not one of
// our own drawings (src/icons/custom.ts). Each SVG becomes the compact form TopicIcon draws:
// parts separated by "|", a path "M…" or a circle "c:x,y,r".
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dir = process.argv[2];
if (!dir || !existsSync(dir)) {
  console.error('Usage: node scripts/vendor-icons.mjs <tabler package/icons/outline folder>');
  process.exit(1);
}

const custom = new Set(
  [...readFileSync('src/icons/custom.ts', 'utf8').matchAll(/^ {2}'?([a-z0-9-]+)'?:/gm)].map(
    (m) => m[1],
  ),
);
const used = [
  ...new Set(
    [...readFileSync('src/data/icons.ts', 'utf8').matchAll(/'([a-z0-9-]+)'/g)].map((m) => m[1]),
  ),
]
  .filter((n) => !custom.has(n) && existsSync(join(dir, `${n}.svg`)))
  .sort();

const attrs = (tag) =>
  Object.fromEntries([...tag.matchAll(/([a-z-]+)="([^"]*)"/g)].map((m) => [m[1], m[2]]));
const n = (x) => String(Number(Number(x).toFixed(3)));

function toParts(svg) {
  const parts = [];
  for (const [tag, name] of svg.matchAll(
    /<(path|circle|rect|line|polyline|polygon|ellipse)\b[^>]*>/g,
  )) {
    const a = attrs(tag);
    if (a.stroke === 'none') continue; // the invisible 24 × 24 frame
    if (name === 'path') parts.push(a.d);
    else if (name === 'circle') parts.push(`c:${n(a.cx)},${n(a.cy)},${n(a.r)}`);
    else if (name === 'line') parts.push(`M${n(a.x1)} ${n(a.y1)}L${n(a.x2)} ${n(a.y2)}`);
    else if (name === 'polyline' || name === 'polygon') {
      const p = a.points
        .trim()
        .split(/[\s,]+/)
        .map(n);
      const pairs = [];
      for (let i = 0; i < p.length; i += 2) pairs.push(`${p[i]} ${p[i + 1]}`);
      parts.push(`M${pairs.join('L')}${name === 'polygon' ? 'z' : ''}`);
    } else if (name === 'ellipse') {
      const [cx, cy, rx, ry] = [a.cx, a.cy, a.rx, a.ry].map(Number);
      parts.push(
        `M${n(cx - rx)} ${n(cy)}a${n(rx)} ${n(ry)} 0 1 0 ${n(2 * rx)} 0a${n(rx)} ${n(ry)} 0 1 0 ${n(-2 * rx)} 0`,
      );
    } else if (name === 'rect') {
      const [x, y, w, h] = [a.x ?? 0, a.y ?? 0, a.width, a.height].map(Number);
      const r = Math.min(Number(a.rx ?? a.ry ?? 0), w / 2, h / 2);
      parts.push(
        r
          ? `M${n(x + r)} ${n(y)}h${n(w - 2 * r)}a${n(r)} ${n(r)} 0 0 1 ${n(r)} ${n(r)}v${n(h - 2 * r)}a${n(r)} ${n(r)} 0 0 1 ${n(-r)} ${n(r)}h${n(-(w - 2 * r))}a${n(r)} ${n(r)} 0 0 1 ${n(-r)} ${n(-r)}v${n(-(h - 2 * r))}a${n(r)} ${n(r)} 0 0 1 ${n(r)} ${n(-r)}z`
          : `M${n(x)} ${n(y)}h${n(w)}v${n(h)}h${n(-w)}z`,
      );
    }
  }
  return parts.join('|');
}

const lines = used.map(
  (name) => `  '${name}': '${toParts(readFileSync(join(dir, `${name}.svg`), 'utf8'))}',`,
);
writeFileSync(
  'src/icons/tabler.ts',
  `// Generated by scripts/vendor-icons.mjs from Tabler Icons (MIT license, see ./TABLER_LICENSE).
// Don't edit by hand: add the icon's name to src/data/icons.ts and run the script again.
export const TABLER = {
${lines.join('\n')}
} as const;
`,
);
console.log(`src/icons/tabler.ts: ${used.length} icons`);
