"""Write the college question indexes from the records and the marks parts.

  python3 research/questions/build_college_index.py

- college/COVERAGE.md: counts by field, source and course, and the topics with no question;
- college/SOURCES.md: how the records were fetched, and each field's sources file;
- college/MARKS.md: every plan's re-marking (marks/<plan>.md), one after another.

Run validate_college.py first; this script trusts the records.
"""

import collections
import glob
import json
import os
import re
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
COLLEGE = os.path.join(HERE, "college")
REPO = os.path.dirname(os.path.dirname(HERE))

# The plan files in the order of docs/RESEARCH_HE.md, with the marks part each group wrote.
PLANS = [
    ("he.math", "Mathematics"),
    ("he.physics", "Physics"),
    ("chemistry", "Chemistry"),
    ("earth-geography", "Earth and geography"),
    ("biology", "Biology and bioengineering"),
    ("mechanical", "Mechanical"),
    ("aero-civil-chemical", "Aero, civil and chemical"),
    ("electrical-computer", "Electrical and computer"),
]


def courses():
    """COURSES from taxonomy.ts: [(id, title, topics)]."""
    out = subprocess.run(
        ["npx", "tsx", "-e",
         "import {COURSES} from './src/data/taxonomy'; "
         "console.log(JSON.stringify(COURSES.map(c => [c.id, c.title, c.topics])))"],
        cwd=REPO, capture_output=True, text=True, check=True).stdout
    return json.loads(out)


def records():
    recs = []
    for p in sorted(glob.glob(os.path.join(COLLEGE, "*.jsonl"))):
        with open(p, encoding="utf-8") as f:
            recs += [json.loads(line) for line in f if line.strip()]
    return recs


def table(head, rows, right=()):
    cells = [head] + [[str(c) for c in r] for r in rows]
    w = [max(len(r[i]) for r in cells) for i in range(len(head))]
    line = lambda r: "| " + " | ".join(c.rjust(w[i]) if i in right else c.ljust(w[i]) for i, c in enumerate(r)) + " |"
    sep = "| " + " | ".join(("-" * (w[i] - 1) + ":") if i in right else "-" * w[i] for i in range(len(head))) + " |"
    return "\n".join([line(head), sep] + [line(r) for r in cells[1:]])


def coverage(recs, cs):
    by_field = collections.Counter(r["field"] for r in recs)
    text = collections.Counter(r["field"] for r in recs if r["content"] == "text")
    by_source = collections.Counter(r["source"]["name"] for r in recs)
    by_course = collections.Counter(r["courseId"] for r in recs)
    topics_hit = collections.Counter()
    for r in recs:
        topics_hit[r["topicId"]] += 1
        for t in r.get("alsoTopics") or []:
            topics_hit[t] += 1
    marks = collections.Counter((r.get("mark") or "unmarked") for r in recs)
    out = ["# College questions: coverage", "",
           "Generated by `build_college_index.py`; don't edit by hand. Records in `*.jsonl`, one",
           "file per field; `content` is \"text\" (copied with attribution, open licences only) or",
           "\"type\" (the question type in our words).", "",
           f"**{len(recs)} records**, {sum(text.values())} with text. Marks: "
           + ", ".join(f"{k} {v}" for k, v in sorted(marks.items())) + ".", "",
           "## By field", "",
           table(["Field", "Records", "Text", "Type"],
                 [[f, by_field[f], text[f], by_field[f] - text[f]] for f in sorted(by_field)], right=(1, 2, 3)),
           "", "## By source", "",
           table(["Source", "Records"], [[s.replace("|", "/"), n] for s, n in by_source.most_common()], right=(1,)),
           "", "## By course", "",
           "Topics: with at least one question (filed or in `alsoTopics`) of the course's topics.", "",
           table(["Course", "Title", "Records", "Topics covered"],
                 [[f"`{cid}`", title, by_course[cid],
                   f"{sum(1 for i in range(len(tp)) if topics_hit[f'{cid}#{i}'])} / {len(tp)}"]
                  for cid, title, tp in cs], right=(2,)),
           "", "## Topics with no question", "",
           "A topic here had no open source the groups could reach (see each field's sources file),",
           "or its questions are filed under a neighbouring topic.", ""]
    for cid, title, tp in cs:
        missing = [f"`#{i}` {t}" for i, t in enumerate(tp) if not topics_hit[f"{cid}#{i}"]]
        if missing:
            out.append(f"- `{cid}`: " + "; ".join(missing))
    return "\n".join(out) + "\n"


def sources(recs):
    by_field = collections.Counter(r["field"] for r in recs)
    files = sorted(glob.glob(os.path.join(REPO, "research/textbooks/sources/he-*.md")))
    rows = []
    for p in files:
        field = re.sub(r"^he-|\.md$", "", os.path.basename(p))
        rows.append([field, by_field.get(field, 0), f"[`sources/he-{field}.md`](../../textbooks/sources/he-{field}.md)"])
    return "\n".join([
        "# College question sources", "",
        "Generated by `build_college_index.py`; don't edit by hand. Reference only: nothing here is",
        "used in a lesson, a picture or a test (`docs/RESEARCH_HE.md`, \"Rules\").", "",
        "Fetched 2026-10-02 by four research groups, sequentially, at most one request per second per",
        "host, with the User-Agent `EducationalCalculatorResearch/0.3 (offline study-app research;",
        "contact …)`, after reading each host's robots.txt. A host the environment's proxy or the",
        "site blocked (bot checks, logins, robots.txt) was noted and skipped, never worked around.",
        "OpenStax books: titles only (no `/books/` page fetched). Question text is copied only from",
        "public-domain, CC BY and CC BY-SA sources, with attribution; every other source is",
        "recorded by type.", "",
        "Each field's sources file quotes every licence or reuse statement with its URL, what",
        "robots.txt said, what was skipped and why, and how open licence questions were settled.", "",
        table(["Field", "Records", "Sources file"], rows, right=(1,)), ""])


def marks():
    out = ["# College plans re-marked against the questions", "",
           "Generated by `build_college_index.py` from `marks/<plan>.md`; edit those. Each part lists,",
           "per topic, the plan row, its old and new mark (Solves, Partly, No, or a `[new-page]` row) and",
           "the record ids that show why, then the taxonomy gaps the records reveal (\"Not in the",
           "taxonomy\", for `docs/HE_TAXONOMY_GAPS.md`).", ""]
    for slug, title in PLANS:
        p = os.path.join(COLLEGE, "marks", f"{slug}.md")
        if not os.path.exists(p):
            out += [f"## {title}", "", "Not re-marked yet.", ""]
            continue
        with open(p, encoding="utf-8") as f:
            body = f.read().strip().splitlines()
        if body and body[0].startswith("# "):
            body = body[1:]
        # One level down, so each plan is a section of this file.
        body = [("#" + l) if l.startswith("#") else l for l in body]
        out += [f"## {title}", ""] + body + [""]
    return "\n".join(out)


def main():
    recs = records()
    cs = courses()
    for name, text in (("COVERAGE.md", coverage(recs, cs)), ("SOURCES.md", sources(recs)), ("MARKS.md", marks())):
        with open(os.path.join(COLLEGE, name), "w", encoding="utf-8") as f:
            f.write(text)
        print("wrote", os.path.join("research/questions/college", name))


if __name__ == "__main__":
    main()
